(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.play_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.text = new cjs.Text("play", "24px 'Arial'");
	this.text.lineHeight = 29;
	this.text.lineWidth = 100;
	this.text.parent = this;
	this.text.setTransform(56,17.9);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(4));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.2,1,1).p("AtHllIaPAAIAALLI6PAAg");
	this.shape.setTransform(84,35.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AtHFmIAArLIaPAAIAALLg");
	this.shape_1.setTransform(84,35.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,170,73.6);


// stage content:
(lib.balantree = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* Mouse Click Event
		Clicking on the specified symbol instance executes a function in which you can add your own custom code.
		
		Instructions:
		1. Add your custom code on a new line after the line that says "// Start your custom code" below.
		The code will execute when the symbol instance is clicked.
		*/
		
		this.play_btn.addEventListener("click", fl_MouseClickHandler.bind(this));
		
		function fl_MouseClickHandler()
		{
			this.gotoAndPlay(0);
		}
	}
	this.frame_57 = function() {
		/* Stop at This Frame
		The Flash timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(57).call(this.frame_57).wait(15));

	// tree
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#663300").s().p("AgPDQIAYmrIAHGvQgLAIgGAAQgKAAgEgMg");
	this.shape.setTransform(263.1,660);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#663300").s().p("AgdFQIAuqyIANK5QgUAMgNAAQgSAAgIgTg");
	this.shape_1.setTransform(261.9,646.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#663300").s().p("AgoGeIA+tRIATNaQgbANgSAAQgZAAgLgWg");
	this.shape_2.setTransform(260.9,638.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#663300").s().p("AgyHrIBNvwIAYP7QgiAQgXAAQgeAAgOgbg");
	this.shape_3.setTransform(259.9,630.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#663300").s().p("AgyIUIBNxEIAYRQQgiARgXAAQgeAAgOgdg");
	this.shape_4.setTransform(259.9,625.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#663300").s().p("AgyI9IBNyYIAYSlQgiASgWAAQgfAAgOgfg");
	this.shape_5.setTransform(259.9,621.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#663300").s().p("AgLJtQgUAAgRgHQgEgKgCgNIgBgCIBFy5IABABIAnRkIAAAAIACBNIgBACIABAVIgKAJQgVAFgTABIgMABIgFAAg");
	this.shape_6.setTransform(259.3,619.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#663300").s().p("AgCKIQgKAAgIgBIgpgDIACgaIgCgEIA+zxIA5SvIABAAIADBQIgCABIABAXg");
	this.shape_7.setTransform(258.7,617.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#663300").s().p("AA4KjIg4gEIgEAAQgIABgHgBIgDgBIgmgCIgBgBIACgaIgBgCIgBgCIAAgBIAhqhIABAJIAUABIAIABIAfACIAaJMIABAAIADBTIgBACIAAAFIgBACIABAPQgCAEgCAAIgBAAgAAApvIABgzIABABIAFBgIgHBFIAAhzg");
	this.shape_8.setTransform(258.7,614.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#336600").s().p("AAnFSIgfgCIgIAAIgUgBIgCgJIAAgBIAAgGIgBgBIABgIIgVgCIABgNIgBgCIAAgBQAkkzALkuIACAqIAAAQIAABzIAHhGIAPh8QAQFGgBEqIAAAoIgBAMIgDAAg");
	this.shape_9.setTransform(258,578.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#009900").s().p("AABAbIAAgBIAAAAIgBgBQgLgeA0gRQABAygoAAIgBgBgAgngbQApARgKAfIAAABIAAABIgBAAQggAAACgyg");
	this.shape_10.setTransform(258.8,539.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#663300").s().p("AgCK5QgKABgIgCIgpgCIACgdIgCgEIA+1SIAAABIAAABIABABIA4UHIABAAIADBXIgCABIABAZg");
	this.shape_11.setTransform(258.7,612.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#009900").s().p("AABAbIAAgBIAAAAQgNgfA1gRQABAygoAAIgBgBgAgngbQApARgKAgIAAAAIAAABIgBAAQggAAACgyg");
	this.shape_12.setTransform(259.6,538.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#663300").s().p("AgCK+QgKABgIgCIgpgDIACgdIgCgDIA+1bIA5UTIABAAIADBXIgCABIABAYg");
	this.shape_13.setTransform(258.7,611.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#009900").s().p("AABAbIAAAAIAAgBQgNgfA1gRQABAxgoABIgBgBgAgngaQApAQgKAfIAAABIAAABIgBAAQggAAACgxg");
	this.shape_14.setTransform(241.2,513.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#663300").s().p("AA6M8QgKABgIgCIgogCIACgdIgCgEIA0xwIgBgBIgHgwIgzjPIgXg1IhcizIAWAYIAZAnIAhA2IAWAuIAbBAIAeBNIAUBfIAGiSIA5UTIABAAIACBXIgCABIABAZg");
	this.shape_15.setTransform(252.6,599.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#000000").ss(0.2,1,1).p("ACqOcIAChBQgEjrgXj1QALjUgcj1QgEh1ggh5QgWiIhZivQgjhFg8hNQADhcBDg6QhHA5gOBBIgyheQgDgEgCgFAiZsJQALATANAUQBfBvA0DHIAEAJQAmCbgFB/QADCGgPCEQgTDRgJDRQgUC6gEC/ICzAAIAPAA");
	this.shape_16.setTransform(249.6,589.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#663300").s().p("AgCOcQACi/AWi6QAIjRATjRQAPiEgDiGQAFh/gmibIgDgJQg1jHhfhvIgXgnIgQg7IgQhEIAFAJIAyBeQAOhBBIg5QhEA6gDBcQA8BNAjBFQBZCvAWCIQAgB5AEB1QAcD1gLDUQAXD1AFDrIgCBBg");
	this.shape_17.setTransform(249,589.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#000000").ss(0.2,1,1).p("ADhQhIAChBQgFjsgWj1QAKjUgcj2QgEh0gfh4QgXiJhaivQgihEg7hOQADhbBCg7QhGA5gOBCIgzheQg5hsgfiDAjuwgQAWB9AsB+QAeBcBDBrQBeBvA2DIIAEAJQAlCbgFB+QADCFgPCGQgSDRgJDQQgWC6gDDAIC0AAIAOAA");
	this.shape_18.setTransform(244.2,576.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#009900").s().p("AABAbIAAgBIAAAAQgNgfA1gRQABAygoAAIgBgBgAgngbQAoARgIAeIgBABIAAABIAAAAIAAABIgBAAQggAAACgyg");
	this.shape_19.setTransform(221.2,468.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#663300").s().p("AAzQiQADjAAWi6QAJjQASjRQAPiGgDiFQAFh+glibIgEgJQg2jIhehvQhDhrgehcQgsh+gWh9IAAAAIAAgBIABgBIAEAEQAJAbAMAaQAfCDA4BsIAzBeQAOhCBGg5QhCA7gDBbQA6BOAjBEQBaCvAXCJQAfB4AEB0QAcD2gKDUQAWD1AFDsIgCBBg");
	this.shape_20.setTransform(243.6,576.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#000000").ss(0.2,1,1).p("ADuR4IAChBQgFjrgWj1QAKjUgcj2QgEh1gfh4QgXiIhaivQgjhFg6hNQADhcBCg6QhGA5gOBBIgzheQg7hwgfiJIgxjbIAMBLQASCtA+CyQAeBcBDBrQBeBvA2DHIAEAJQAlCbgFB+QADCGgPCFQgSDRgJDRQgWC6gDC/IC0AAIAOAA");
	this.shape_21.setTransform(242.9,567.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#009900").s().p("AABAcIAAgCIAAAAQgNgfA1gRQABAygoAAIgBAAgAgngbQApASgKAeIAAABIAAABIgBAAQggAAACgyg");
	this.shape_22.setTransform(218,450);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#663300").s().p("ABAR4QADi/AWi6QAJjRASjRQAQiFgEiGQAGh+gmibIgEgJQg1jHhehvQhEhrgehcQg9iygTitIgMhLIAxDbQAgCJA6BwIAzBeQAOhBBGg5QhCA6gDBcQA7BNAiBFQBaCvAXCIQAfB4AFB1QAcD2gLDUQAXD1AEDrIgCBBg");
	this.shape_23.setTransform(242.3,567.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#009900").s().p("AABAbIAAgBIAAAAQgNgfA1gRQABAygogBIgBAAgAgngbQApARgKAgIAAAAIAAABIgBAAQggAAACgyg");
	this.shape_24.setTransform(218,451.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#492513").s().p("AhVM7IACg5QgFjsgWj1QAKjUgcj1QgBgvgGgvQAXiEA6hvQA8iRBbhpQAVgjASgkQgEAhgMAgIgVA8IgYAhQiGDLgUEEQAnIDANIFg");
	this.shape_25.setTransform(275.3,598.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#663300").s().p("ABAR4QADi/AWi6QAJjRASjRQAQiFgEiGQAGh+gmibIgEgJQg1jHhehvQhEhrgehcQg9iygTitIgMhLIAxDbQAgCJA6BwIAzBeQAOhBBGg5QhCA6gDBcQA7BNAiBFQBaCvAXCIQATBJAJBGQAGAvACAvQAcD2gLDUQAXD1AEDrIgCA5IAAAIg");
	this.shape_26.setTransform(242.3,567.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#009900").s().p("AABAbIAAgBIAAAAQgNgfA1gRQABAygoAAIgBgBgAgngbQApARgKAfIAAABIAAABIgBAAQggAAACgyg");
	this.shape_27.setTransform(218.4,450.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#492513").s().p("Ah9OUIACg5QgFjrgXj1QALjUgcj1QgCgvgGgvQAYiFA5hvQA+iRBahpQA8hmAmhoIALgrIABAPIAJAeQgUBHgdBEQgbBDhBBWQiGDKgVEEQAoIEANIEg");
	this.shape_28.setTransform(279.3,589.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#492513").s().p("AiYQeIACg5QgFjsgXj0QALjVgcj1QgCgvgGgvQAYiEA5hvQA+iRBahpQA8hnAmhnIAzjNQAGg3AOg5IAAgCIADAQIABAGQgMA9gGBIQgXCeg+CTQgbBDhBBVQiGDLgVEDQAoIEANIFg");
	this.shape_29.setTransform(282,575.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#492513").s().p("AizRoIACg5QgFjsgXj1QALjUgcj2QgCgvgGgvQAYiDA5hvQA+iRBahpQA8hnAmhnIAzjNQAGg4AOg4QAEgbAMghQAGgYAPggIAVgiQg3BxgRC+QgXCdg+CUQgbBChABWQiHDLgVEDQAoIEANIFg");
	this.shape_30.setTransform(284.7,568.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#939E36").s().p("AgRAZIgBgBIAAgBQgNgeA0gRQACAxgnAAIgBAAg");
	this.shape_31.setTransform(246.2,495.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#009900").s().p("AABAbIAAAAIAAgBQgNgfA1gRQABAxgoABIgBgBgAgngaQAfAMACAVIAAACQAAAGgCAGIAAABIAAABIgBAAQggAAACgxg");
	this.shape_32.setTransform(218.4,452.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#663300").s().p("ABAR2QADi/AWi7QAIjQATjRQAPiFgDiHQAFh9gmibIgDgJQg2jHhehwQhEhqgdhdQg+ixgSiuIgMhEIAAgCIAxDXQAfCJA7BwIAyBeQAOg+A+g2IAAABQg6A5gDBWQA7BNAjBFQBaCvAWCIQATBIAJBGQAGAwACAvQAcD1gLDVQAXD0AFDsIgCA5IAAAIg");
	this.shape_33.setTransform(242.3,567.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#009900").s().p("AABAbIAAgBIAAAAQgNgfA1gRQABAygoAAIgBgBgAgngbQAkAPgDAaIAAAAIgCAHIAAABIAAABIgBAAQggAAACgyg");
	this.shape_34.setTransform(218.4,452.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#663300").s().p("ABAR3QADjAAWi6QAJjQASjSQAPiFgDiGQAFh9glicIgEgJQg2jHhehvQhDhrgehcQg+iygSitIgMhHIAAAAIAxDYQAfCIA7BxIAzBdQANg9A+g2IABAAQg7A5gCBWQA6BNAjBFQBaCvAXCJQATBIAJBGQAGAvABAvQAcD2gKDUQAWD1AFDsIgCA5IAAAIg");
	this.shape_35.setTransform(242.3,567.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#939E36").s().p("ACJD8IgBgBIAAAAQgOggA2gRQACAzgpgBIAAAAgAh5iwIgBgCIAAgBQgRgvBFgaQACBMg0AAIgBAAgAivj8QA3AagOAvIAAABIgBACIgBAAQgpAAAChMg");
	this.shape_36.setTransform(230.7,472.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#663300").s().p("ABAR4QADi/AWi6QAJjRASjRQAQiFgEiGQAGh+gmibIgEgJQg1jHhehvQhEhrgehcQg9iygTitIgMhLIAxDbQAgCJA6BwIAzBeQANg9A/g2IAAAAQg6A5gDBWQA7BNAiBFQBaCvAXCIQATBJAJBGQAGAvACAvQAcD2gLDUQAXD1AEDrIgCA5IAAAIg");
	this.shape_37.setTransform(242.3,567.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#939E36").s().p("AACAmIgBgCIAAAAQgRgvBFgaQACBLg1AAIAAAAgAgzglQA1AagMAvIAAAAIgBACIgBAAQgpAAAChLg");
	this.shape_38.setTransform(218.3,450.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#009900").s().p("AlPDtIgBgBIAAgBQgNgfA1gSQACAzgpAAIAAAAgAEsi6IAAAAIAAgBQgOggA2gRQABAygoABIgBgBg");
	this.shape_39.setTransform(278,474.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#939E36").s().p("AACAmIgBgCIAAAAQgRgvBFgaQABBLg0AAIAAAAgAgzglQA1AagMAvIAAAAIgBACIgBAAQgpAAAChLg");
	this.shape_40.setTransform(218.4,450.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#009900").s().p("Ak8DtIgBgBIAAgBQgNgfA1gSQACAzgoAAIgBAAgAlmC2QAqARgKAgIAAAAIgBABIAAAAQggABABgzgAE/i6IAAAAIAAgBQgOggA2gRQABAygoABIgBgBgAEUjsQAqARgKAgIAAABIgBAAIAAABQggAAABgzg");
	this.shape_41.setTransform(276.1,474.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#939E36").s().p("AACAlIgBgBIAAgBQgRguBFgaQABBLg0gBIAAAAgAgzglQA1AagMAuIAAABIgBABIgBAAQgpABAChLg");
	this.shape_42.setTransform(218.5,450.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#009900").s().p("AkBDEQAqARgKAgIAAAAIAAABIgBAAQggABABgzgAi1DjIgBgBIAAAAQgOggA2gRQABAzgogBIAAAAgAjfCsQAqARgLAhIAAAAIAAABIgBAAQgfAAABgzgAntieQAtgGAHAhIAAAAIAAACQgIAEgHAAQgUAAgRghgAHBiaIgBAAIgBgBQAEghAzAKQgRAcgUAAQgIAAgIgEgAFujCQAtgGAGAhIAAAAIAAACQgHAEgHAAQgUAAgRghgAn1jLQAtgGAHAhIAAAAIAAACQgHAEgIAAQgTAAgSghgAHGjDIgBgBIAAgBQgNggA2gQQABAygoAAIgBAAgAGbj1QAqAQgLAgIAAABIAAABIgBAAQgfAAABgyg");
	this.shape_43.setTransform(262.7,475.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#B6C461").s().p("AhECYQgTAEgHgGQgEgDAAgGIgMABQgnABgYgYQgRgPgMgcQAlAbAvAAIANAAQATgCAVgGQA8gLAPg3QAMgbgMgaQAiAKAjggQAXgZgKgVQgCgbgJgJQgRgVgPgCQAQgEASAEQAUAGASAJQARAJANAZQAJASAAAVQAHAXgKAbQCFB8j3gDQgNANgVAIQgQARgSgBQgPAJgOAAQgHAAgHgCg");
	this.shape_44.setTransform(232.1,460);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#CADC69").s().p("AhfCWIgFgDQgwgKgFggQgrgIgEguQgKgzBRgeQgTgkAhgTQAngdAbAZQgKg6BLgWQAwgVAuAqQAcAbASAsQAPACARAVQAJAJACAbQAKAUgXAZQgjAggigKQAMAbgMAbQgQA3g8ALQgUAGgUACIgMAAQgvAAglgbg");
	this.shape_45.setTransform(221.4,452.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#D2E077").s().p("AhzCwQhXgbgDhoQgChIBFgZQADgeAdgSQAkgUAfAJQABgxBDgQQAlgIArAIQAbAEAZAYQASAOALAWQANAjADAiQgSgrgcgcQgugqgwAVQhLAWAJA6QgagYgnAdQghASATAjQhRAeAKA1QAEAuArAIQAFAfAwAKg");
	this.shape_46.setTransform(216.4,449.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#663300").s().p("AAwQQQADjAAWi6QAIjQATjSQAPiFgDiFQAFh+gmicIgDgJQg2jHhehvQhEhrgdhcQgmhtgWhqIANgBQAAAGAEADIAAABQAfCIA7BxIAyBdQAOg9A+g2IAAAAQg6A5gDBWQA7BNAjBFQBaCvAWCJQATBIAJBHQAGAvACAuQAcD2gLDUQAXD1AFDsIgCA5IAAAIg");
	this.shape_47.setTransform(243.9,578.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#009900").s().p("Al6DEQAqARgLAgIAAAAIAAABIgBAAQggABACgzgAkvDjIgBgBIAAAAQgOggA2gRQACAzgpgBIAAAAgAlZCsQAqARgKAhIAAAAIgBABIgBAAQgfAAABgzgAFHiaIgBAAIgBgBQAEghAzAKQgRAcgUAAQgIAAgIgEgAD0jCQAtgGAHAhIAAAAIAAACQgIAEgHAAQgTAAgSghgAFMjDIAAgBIAAgBQgOggA2gQQABAygoAAIgBAAgAEhj1QAqAQgKAgIAAABIgBABIgBAAQgfAAABgyg");
	this.shape_48.setTransform(274.8,475.3);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#CADC69").s().p("An3CWIgFgDQgwgKgFggQgrgIgEguQgKgzBRgeQgTgkAhgTQAngdAbAZQgKg6BMgWQAwgVAuAqQAcAbASAsQAPACARAVQAJAJACAbQAKAUgXAZQgjAggigKQAMAbgMAbQgQA3g8ALQgUAGgUACIgNAAQgvAAglgbgAHUBmIgcgDIgMgCIgHgCQgZgIgJgTQgGgIACgJIAEgHIgIABQgTABgVgNQgQgLAHgKQABgMAGgDQAMgKALgBQANgUATgMQAggUAhAKQA2AKgHAbQATgMAbAOQAXAIgNAQQA4ANgHAZQgCAVgeADQgEAPghAEIgEACQgaAMghAAIgJAAg");
	this.shape_49.setTransform(262.2,452.6);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#D2E077").s().p("ApLCwQhXgbgDhoQgChIBEgZQADgeAegSQAkgUAfAJQAAgxBFgQQAlgIAqAIQAbAEAaAYQARAOALAWQAOAjACAiQgSgrgbgcQgvgqgvAVQhMAWAJA6QgagYgoAdQggASASAjQhRAeALA1QADAuArAIQAFAfAwAKgAIyBoQAegEADgVQAHgYg5gOQANgQgWgJQgcgNgTALQAHgag1gKQghgJghATQgTAMgMAUQABgQAKgPQAHgKANgHQARgLATgCQAegDAaADQAwAIAAAWQAWgEAZAJQAVAIACANQAWAFATAKQAXAMAUASQAaAZhFAVQgXAHgjAHIgtADQAigFADgOg");
	this.shape_50.setTransform(263.6,449.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#492513").s().p("AihQ6IABg5QgEjsgXj1QALjUgcj2QgCgugGgvQAXiEA6hvQA+iRBahpQA8hnAmhnIAzjNQAGg4AOg4QAEgaALggIAIACQgaBZgLB4QgXCdg+CUQgbBChBBWQiGDLgVEDQAoIEANIFg");
	this.shape_51.setTransform(282.9,573);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#009900").s().p("Ag4gNQAqAQgLAgIAAABIAAABIgBAAQggAAACgygAASASIgBgBIAAgBQgNgeA1gSQACAygoAAIgBAAgAgXgkQApARgKAfIAAAAIgBABIAAAAQgfABABgyg");
	this.shape_52.setTransform(242.6,496.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#B6C461").s().p("AmBCYQgTAEgHgGQgEgDAAgGIgMABQgnABgYgYQgRgPgMgcQAmAbAuAAIAOAAQATgCAUgGQA8gLAQg3QAMgbgMgaQAiAKAjggQAXgZgKgVQgCgbgJgJQgRgVgPgCQARgEARAEQAUAGASAJQARAJANAZQAJASAAAVQAHAXgKAbQCFB8j3gDQgNANgUAIQgSARgSgBQgPAJgOAAQgHAAgHgCgAGUAyIgHgCIgBAAQgMAAgNgIQgOgDgJgGQitABBdg5QgGgMAEgKQAAgKAHgIQAJgMALgEQANgEAOgDQAMgCAMACQgLABgMAKQgGAEgBAMQgHAKAQALQAVANATgBIAIgBIgDAHQgDAJAGAIQAJASAZAIIAIACIALACIAcADIAJAAQAhAAAagMQgIANgMAHQgRALgbgBIgJAAQAAADgDABQgFADgNgCIgKABIgMgCg");
	this.shape_53.setTransform(263.8,460);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#663300").s().p("AAwQQQADjAAWi6QAIjQATjSQAPiFgDiFQAFh+gmicIgDgJQg2jHhehvQgxhOgdhGQANAAASgDIAvBYQAJgpAggmIAHAAQgfAugCA9QA7BNAjBFQBaCvAWCJQATBIAJBHQAGAvACAuQAcD2gLDUQAXD1AFDsIgCA5IAAAIgAips2QgmhtgWhqIANgBQAAAGAEADIAAABQAXBnAoBYQAAAFACADIgTAQIgDgJg");
	this.shape_54.setTransform(243.9,578.1);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#CADC69").s().p("AjDFEIgDAAIgKgCIgLgBQgLgDgFgHQgIgOAOgIIAEgDIgHAAQgLgBgJgCIgKgEQgggOAPgUQAEgHAGgGIAEgEQATgPAhgHIAEgBQAZgOAYAEQAWgMAhAFQApAFgKAdQAgAAABANQAFAQgbAFQAsAGgOAaQgEASgvAIQgTADgWAAIgZAAQgIAFgVACIgIABIgIgBgAn3ADIgFgDQgwgKgFgfQgrgIgEguQgKg1BRgeQgTgkAhgSQAngdAbAYQgKg6BMgWQAwgVAuAqQAcAcASArQAPADARAVQAJAIACAbQAKAVgXAZQgjAggigJQAMAbgMAbQgQA1g8AMQgUAGgUABIgNABQgvAAglgbgAHUgsIgcgEIgMgCIgHgBQgZgIgJgTQgGgJACgJIAEgHIgIABQgTABgVgMQgQgMAHgJQABgNAGgEQAMgJALgBQANgUATgNQAggTAhAJQA2AKgHAbQATgLAbANQAXAJgNAQQA4AOgHAYQgCAVgeAEQgEAOghAFIgEACQgaAMghAAIgJAAg");
	this.shape_55.setTransform(262.2,467.4);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#B6C461").s().p("AkPEZQgSgBgPgHIgOACQgSADgNAAQhAACAwgsIATgQQgCgDAAgFIABgGQgFgIAHgFQgBgJANgFQAEgHAHgBQADgBAFABIALgQQAJgPAWgFQAWgGAVAUQghAHgTAPIgEAEQgGAGgEAHQgPAUAgAOIAKAEQAJACALABIAHAAIgEADQgOAIAIAOQAFAHALADIALABIAKACIADAAQAKABAGgBQAVgCAIgFQgEAGgJAFIgaAKIgSADIgHAAIgKAAIgEABQgOAAgNgEgAmBAVQgTAFgHgGQgEgDAAgHIgMABQgnABgYgWQgRgPgMgcQAmAbAuAAIAOgBQATgBAUgGQA8gMAQg2QAMgbgMgbQAiAJAjggQAXgZgKgVQgCgbgJgIQgRgVgPgDQARgEARAEQAUAGASAKQARAJANAZQAJARAAAWQAHAXgKAaQCFB+j3gDQgNANgUAHQgSARgSgCQgPAKgOAAQgHAAgHgDgAGUhPIgHgCIgBgBQgMABgNgIQgOgEgJgGQitABBdg5QgGgMAEgLQAAgKAHgIQAJgLALgEQANgFAOgCQAMgCAMACQgLABgMAJQgGAEgBANQgHAJAQAMQAVAMATgBIAIgBIgDAHQgDAJAGAJQAJATAZAIIAIABIALACIAcAEIAJAAQAhAAAagMQgIANgMAGQgRALgbAAIgJgBQAAADgDABQgFADgNgCIgKABIgMgBg");
	this.shape_56.setTransform(263.8,473.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#D2E077").s().p("AhmFVIglgCQAWAAATgDQAvgIADgSQAOgagsgGQAbgFgFgQQAAgNggAAQAKgdgpgFQghgFgWAMQgYgEgZAOIAcgTQAZhBBHAaQBHAaABAoQAUAFABAMQAAAOgSAIQAiAHASAWQARAWguAGIhAAJQgKABgMAAIgPAAgApLAQQhXgagDhoQgChJBEgZQADgeAegSQAkgUAfAJQAAgxBFgQQAlgIAqAIQAbAEAaAYQARAOALAWQAOAjACAiQgSgrgbgcQgvgqgvAVQhMAWAJA6QgagYgoAdQggASASAkQhRAeALA1QADAuArAIQAFAeAwAKgAIyg3QAegEADgVQAHgYg5gOQANgQgWgJQgcgNgTALQAHgbg1gKQghgJghATQgTANgMAUQABgQAKgQQAHgKANgHQARgLATgCQAegDAaADQAwAIAAAWQAWgEAZAJQAVAJACANQAWAFATAKQAXAMAUASQAaAZhFAVQgXAHgjAHIgtADQAigFADgOg");
	this.shape_57.setTransform(263.6,465.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#663300").s().p("ABWLSQAKjjAWjkQASiSgEiRQAGiKgsiqIgFgJQg/jahwh5Qg6hVgihMIAlgDIA4BgQALgtAlgpQgcAygCBCQBFBVAqBKQBqC/AbCVQAWBPALBNIAAACIACANIAHBXIAAAFIABAEIAAAFIAVHDIgCAcIABADIgBADQAbEHAGD8IgBARIgBAmIAAABIAAAQIjWAJQAEjRAajLgAjIuBQguh3gZh0IAPgBQAAAEACADQAgB3AtBeQAAAEADAFQgOAJgJAIIgDgKg");
	this.shape_58.setTransform(240.3,568.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#492513").s().p("Ai2SZIgGgQIgBgBIACgmIAAgRQgGj8gbkHIABgDIgBgDIACgcIgUnDIgBgFIAAgEIgBgFIgHhYIgBgMIAAgCQAbiQBEh5QBHibBohyQBMh1AqhoIAHgYIA2jIIAEgXQAGgyAOgwIAFgXQAEgUAJgVIAGgBIgBAGIABAGQgbBagLBzIgDAUQgEAagFAaQgdCHg7CAIgGANQgfBEhFBUIgNAUQiUDUgaELIABAiQAtImAPInIgEACg");
	this.shape_59.setTransform(286.3,562.9);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#D2E077").s().p("AhbFzIgsgBQAagBAWgCQA4gKAEgTQARgdg0gGQAggFgGgSQgBgOgmAAQAMgfgwgGQgogGgaANQgNgCgPADIgDABQgNADgOAGIAGgDIAcgSQAdhGBUAcQBUAcACAsQAWAFACANQAAAQgVAJQApAIAVAYQAUAYg3AGIhLAJQgMACgOAAIgSgBgAqaARQhngdgDhxQgDhPBRgcQAEggAjgUQArgWAkAKQABg2BRgRQAsgIAyAIQAgAEAeAbQAVAPANAYQAQAmADAmQgVgwghgeQg3gug4AXQhaAYALA/QgfgagvAfQgmAVAVAnQhgAgANA6QAEAyAzAJQAGAhA5ALgAL8g8IgPgDIgagHQgVgEgYgDQAZgIgHgNQAMgGgIgOIABgEQAAgOgWgKQgEgGgNgFQgMgFgKgBQgGgJgXgEIgGgBQgZgHgUALQACgTgrgFIgKgBQgVgCgVAMQgPAOgKARIgDAFIABgDQAEgOAKgOQAJgKANgHQAbgPAdACQAtABARAMQAsACAMAVQAaAAANAMQApALgCATQAPALACAIQAQAOAAAPQAXAPgUAMQAPAEgfADQAKgDAGgEg");
	this.shape_60.setTransform(260.7,444.9);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#CADC69").s().p("AjhFiIgEgBIgMgCIgNgBQgNgDgGgIQgJgPARgJIAEgCIgHAAIgBAAQgNgBgLgDQgGgCgGgDQglgPARgVQAFgIAHgHIABgBQAUgOAagJIATgEIALgFIgGAEQAOgHANgDIADgBQAPgCANACQAagNAoAGQAwAFgMAgQAmAAABANQAGASggAFQA0AHgRAdQgEATg4AJQgWADgaAAIgeAAQgKAFgZACIgLABIgHAAgAniAgQg5gBgogVIgLgHIgGgDQg5gKgGgjQgzgJgEgyQgNg5BgghQgVgnAmgUQAvggAfAbQgLg/BagYQA4gXA3AuQAhAeAVAvQASADAVAXQAKAJACAdQAMAXgbAcQgqAigogKQAOAegOAdQgTA6hHANIgMADQgRAEgRABIgIAAgAI8gwIgGAAIgEAAIgDAAIgHgBIgXgDIgCAAIgBAAIgDAAIgHgBIgBAAIAAAAIgBgBIgBAAIAAAAIgCAAIgEgBIgHgDQgYgIgLgRIgBgBIAAgBIgBAAQgEgGAAgGIAAgBIAAgBIABgDIAAgBIAAgCIABgCIABgCIABgCIgBAAIAAAAIgEAAIgCAAIgDAAIgCAAIgBAAIgJgBQgRgCgRgJQgNgJAAgHQAAgEACgEIACgIIADgFIADgDIACgCQANgJALgCIABAAIgBAAIADgDIgBADIADgEQAJgSAQgNQAVgNAVACIAKACQArAFgCATQAUgLAZAGIAGACQAXAEAGAIQAKACAMAFQANAEAEAGQAWAKAAAPIgBADQAIAPgMAFQAHAOgZAIQAYACAVAEQgIAHgQACIgFADQgGANghAFIgFABIgFADIgTAGIgVAEIgZACIgBAAg");
	this.shape_61.setTransform(261.4,447.3);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#B6C461").s().p("Al4EBIglADQhMADA5gxQAJgIAOgJQgIgYAJgGQgCgJAPgGQAGgHAHgBQAEgBAGABIANgSQALgQAagGQAagHAYAWIgSAFQgaAIgUAPIgCABQgHAGgFAIQgRAWAmAPQAFADAHABQALADANABIAAAAIAIAAIgFADQgQAJAIAPQAHAIAMADIANABIANACIADAAQAMABAHgBQAZgCAJgFQgFAGgKAFIgfALQgIACgNABIgIABQglApgLAtgAnIgTQgWAEgIgGIgDgDQgCgCAAgFIgPABQgtABgdgZQgUgRgPgeIAMAHQAnAVA6ABIAHAAQARgCASgEIAMgDQBGgMAUg8QAOgdgOgdQAoAKApgjQAbgbgLgXQgCgegLgJQgUgXgTgCQAVgFAUAFQAYAGAVAKQAUAKAPAbQAMATAAAYQAHAZgLAdQCdCIkkgCQgPAOgZAIQgVATgVgBQgRAKgRAAQgJAAgIgDgAHfiBIgCgBIgGgBIgBgBIgBAAQgOAAgOgIIgEgBIgOgEIgLgGIAAAAQjLABBrg9IABgEQgGgLAEgKIAAgBQAAgLAHgIQALgMALgEQATgGAOgDQAQgCANACIABAAIgCAAQgLACgNAIIgCACIgDADIgCAGIgCAIQgDADAAAEQABAIANAIQAQAKARACIAKABIABAAIACAAIADAAIABAAIAEgBIABAAIAAABIgBABIAAACIgBACIgBADIAAAAIAAADIAAACIAAAAQAAAGAEAGIAAAAIABACIABABQAKARAYAIIAIACIADABIADABIAAAAIAAAAIABAAIAAAAIACAAIAGABIADABIACAAIACAAIAWADIAHAAIADAAIAFAAIAGAAIABAAIAYgBIAVgEQALgDAKgEIABAAQgKAMgMAHIgDACQgUALgeAAIgDAAIgHAAIgCABQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgGADgPgCIgBAAIgMABIgNgBg");
	this.shape_62.setTransform(263.8,457.8);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#663300").s().p("ABkMOQALj2Aaj3QAViegEidQAGiWgzi3IgGgKQhJjsiBiEQhChcgohSQARAAAagEIA/BpQANgxArgtQggA2gCBIQBQBcAwBRQB7DPAeChQAaBWANBUIAAABIACANIAIBfQAeDlgCDMIgDBbIgBANIAAADIAAADIAAAFIADASIAWERIAMEFIAAAHIAAADIgCAyIgBARIj2AJQAFjiAejcgAjnvMQg1iAgdh+IASgBQAAAFACADQAkCBA0BlQAAAFAEAEQgQAKgLAJIgDgLg");
	this.shape_63.setTransform(236.7,558);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#492513").s().p("AjNT6IgOgLIAAgGIACgyIAAgCIAAgIIgMkEIgXkRIgCgTIAAgEIAAgDIAAgDIAAgNIADhbQADjMgfjlIgIhgIgBgNIAAgBQAficBPiDQBSinB2h6QBWh9AyhvIAKgaIA9jZIAGgZQAHg1APg2IAGgYQAEgVAKgYIAGgEIABgBIAFAFQggBhgOB+IgCAVIgLA5QghCThDCMIgHAOQgjBIhPBbIgPAVQisDjgfEfIgCAlQA1JYASJYIgEAFg");
	this.shape_64.setTransform(290,552.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#B6C461").s().p("AmyEWQgaAEgRAAQhZADBCg1QALgJAQgKQgJgZAKgHQgCgKASgGQAGgIAJgBQAFgBAGABIAQgUQAMgRAdgGQAegHAdAXIgBABIgWAFQgcAIgWAPIgEACQgHAHgGAJQgUAXArARIAPAEQAMADAPABIAAAAIAJAAQgDABgCACQgUAKALAQQAHAJAPADIAPABIAHACIAIABIADAAQANABAJgBQAcgDALgFQgFAHgNAFIgjAMQgKADgOABIgKAAQgrAtgNAxgAoPgUQgaAEgKgGIgCgDQgCgDAAgFIgSABQg1ABghgcQgXgSgQghIAaAOQApAQA5ACIAKAAQATgCAUgEIAPgDQBRgOAWhAQAQgggQggQAuALAwglQAggegNgZQgDgggMgKQgYgZgVgDQAXgEAXAEQAdAIAYAKQAXALARAeQANAUABAaQAJAbgOAfQC3CUlTgDQgRAPgdAJQgYAVgYgCQgVALgTAAQgKAAgJgCgAIqiMIgCgBIgIgBIAAAAIgCgBIAAAAQgQAAgQgIIgEgCIgRgEIgNgGIAAAAQjpABB4hCIADgEQgIgNAGgLIAAgBQAAgMAIgJQANgNAOgEQAVgHAQgCQATgDAPACIAAAAQgIACgKAEIgNAHIgCACIAAAAQgDADgCAFIgBACIgCAHIgDAFQAAADABAEQACADAEADIABACIAIAFQAVALAVACIAGABIACAAIACAAIACAAIADAAIAEgBIABAAIACACIAAAAIgCAEIgBACIAAABQgEAJAHAKIABABQAJARAYAJIANAFIAHABIAEABIAGABIAEABIABAAIADAAIADABIAEAAIAMACIATACIAEAAIACAAIAKAAIADAAIAZgCIAZgEQANgDAOgFIgBAAQgLAOgPAIIgEABQgVAMghAAIgEAAIgJgBIgCABQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAQgHAEgRgDIgCAAQgGABgHAAIgPgBg");
	this.shape_65.setTransform(263.9,438.6);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#CADC69").s().p("AkJF/IgDAAIgIgBIgHgCIgPgBQgOgDgIgJQgKgQATgKQACgCAEgBIgKAAIAAAAQgPgBgMgDIgPgEQgrgRAUgXQAGgJAIgHIADgCQAWgPAdgIIAVgFIABgBIALgEIgFADIAUgIIAFgBQAWgFASACIACAAQAegOAuAGQA4AHgOAiQAsAAAAAPQAHATgkAFQA8AHgUAgQgEAVhBAJQgaADgeABIgjAAQgLAFgcADIgOABIgIgBgAoyAjQg4gCgqgQIgagOIgHgDQhCgMgHglQg7gJgEg3QgPg+BvgjQgZgrAsgVQA2gjAkAdQgNhFBogZQBBgZBAAxQAmAhAYAzQAVADAYAZQAMAKADAgQANAZggAeQgwAlgugLQAQAggQAgQgWA/hRAOIgOADQgVAEgTACIgKAAgAKRg0IgLAAIgCAAIgEAAIgTgCIgMgCIgEAAIgDgBIgDAAIgBAAIgEgBIgFgBIgFgBIgGgBIgOgFQgXgJgKgRIAAgBQgIgKAEgJIAAgBIABgCIACgEIAAAAIgCgCIgBAAIgEABIgDAAIgCAAIgCAAIgCAAIgGgBQgVgCgVgLIgIgFIgBgCQgEgDgCgDQgBgEAAgDIADgFIACgHIABgCQACgFADgDIAAAAIACgCIANgHQAKgEAJgCIgBAAIACgCIgBACIACgDIARgRQAJgIALgHQAOgHANgEQAcABAFAJQAYgNAfAFIAKABQAmAMgFAWIAEABQAYgKAiANQAJAEAFAEIAAAFIAFADQAOAHAGAGQAGAFACAFQACAIgJAHQAUADASAFQgDADgFADQAJAPgTANIAEACQgJAEgPACIgFAEQgIAOgmAFIgFABIgGADIgXAHIgZAEIgZACIgCAAg");
	this.shape_66.setTransform(261.5,427.2);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#D2E077").s().p("Ah2GTQgSgCggAAQAegBAagDQBAgJAFgVQATggg8gHQAlgFgHgTQgBgPgsAAQAOgig4gHQgtgGgeAOIgCAAQgTgCgVAFIgFABIgUAIIAFgDIAigTQAhhMBhAeQBiAeACAwQAZAFADAOQAAASgYAJQAvAIAXAaQAYAahAAIIhWAJQgPACgRAAIgUAAgAsNATQh3gfgEh7QgDhWBegeQAEgjAogWQAxgXArALQABg7BdgSQAzgKA6AKQAlAEAjAdQAYAQAPAbQASApAEAoQgZgzgmghQg/gxhBAZQhoAZANBFQgkgdg3AjQgsAVAZArQhvAjAPA+QAFA3A7AJQAGAkBCAMgAMzhJIgFgBQATgNgJgPQAGgDADgEQgSgFgUgCQAJgHgDgIQgBgFgHgFQgFgHgOgGIgFgDIAAgFQgFgEgKgEQgigNgYAKIgEgBQAFgWglgMIgLgBQgegFgZANQgEgJgcgBQgNAEgOAHQgLAHgKAIIgRARIgBADIABgDQAHgTARgQQAIgFAIgCIACgBQAkgTAnAGQAzAEANAPQAKACAIADQAdAAATAPIAFACQAcAFABAPQA7ANgFAYQAFAIgDAHIACADQAdAIAZANQAwAUhqAOQAOgJgbgLg");
	this.shape_67.setTransform(261.4,424.6);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#663300").s().p("ABwNLQAOkKAdkKQAYiqgFipQAHihg5jGIgHgLQhTj+iTiOQhLhjgthYQAUAAAdgEIBIBwQAOg1AxgvQgkA5gEBOQBcBjA2BXQCMDfAjCuQAdBcAPBaIAAABIABAHIAJBnIAAAEIABADQAsE5gREMIAAABIAAAFIAAAFIAFAmIAlIwIAAACIgBAYIgCAuIABAAIgBAFIkYALQAGj0AhjsgAkHwXQg7iKghiIIATgBQAAAGADADQApCLA7BtQAAAFAEAFIgdAUIgFgMg");
	this.shape_68.setTransform(233.1,548);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#492513").s().p("AjkVeIgWgFIAAAAIABguIABgYIAAgCIglowIgFgmIAAgFIAAgFIAAgBQARkMgsk5IAAgDIgBgEIgJhnIgBgHIAAgBQAjioBZiNQBciyCEiBQBjiFA4h3IANgbIBFjqIAHgbQAJg6AQg5IAIgbQAEgXAKgZIAFgHIAEgJIAJADQglBogRCJIgCAYQgFAegHAeQglCghMCYIgIAPQgmBMhYBiIgTAVQjCD0gnEzIgDAnQA8KLAVKJIgCAHg");
	this.shape_69.setTransform(293.6,541.8);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#B6C461").s().p("AntEsQgdAEgUAAQhjADBKg5IAegUQgKgcALgHQgCgKAVgHQAGgJAKgBQAFgBAIABIASgVQANgSAigHQAigIAhAZIgCAAIgYAGQgiAKgZAQIgCACQgJAHgIAKQgWAZAyASQAHADAJABQAOAEARABIAAAAIALAAQgEABgCACQgWALAMARQAIAJARAEIAQABIAFABIAMACIAEAAQAPABAJgBQAhgDAMgGQgFAIgPAGQgUAHgUAFQgLADgQABIgMABQgwAwgPA0gApWgWQgdAFgLgHIgDgDQgDgDAAgGIgUABQg7ABgmgdQgagTgTgkIAeAPQAvASBAABIAKAAQAXgCAXgFIAQgDQBcgOAZhGQATgigTgiQA1AMA2gpQAkgggPgbQgCgigOgLQgbgbgYgCQAagGAaAGQAhAHAaAMQAaALAVAgQAPAWAAAcQAJAegOAhQDPCfmAgDQgUAQggAKQgcAWgbgBQgXALgWAAQgLAAgLgDgAJ1iWIgCgBIgJgBIAAgBIgCAAIgBgBQgRABgSgJIgFgCIgSgEIgRgHIgBgBQkFACCGhGIAEgEQgKgPAHgNIAAAAQAAgNAJgKQAPgOARgFQAYgHASgDQAVgCARACQgSACgRALIgCACQgIAGgCANQgLANAZAOQAbAMAWACIAHABIACAAIAFAAIAEAAIACAAIAFgBIAAABIgCACIgCAFIgBADIAAADQgCAIAGAIIABABIABACIAFAFQAPASAfAJIAKACIACAAIABAAIAAAAIABAAIABABIABAAIARACIAZADIAIABIAGAAIABAAIALAAIADAAIAIAAQAXAAAVgEIAagGIAPgFIgBABQgNAPgRAIIgEACQgYAMgkAAIgFAAIgJAAIgEAAQAAADgDABQgJAEgTgDIgBAAQgJACgIAAIgQgBg");
	this.shape_70.setTransform(264,419.4);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#CADC69").s().p("AkvGdIgEgBIgNgCIgEgBIgRgBQgQgDgJgKQgLgRAVgKQACgCAFgBIgLAAIAAAAQgRgBgOgEQgJgCgHgDQgygSAWgZQAHgJAJgIIACgBQAagQAigKIAYgGIABAAIAPgFIgIAEQARgHAPgEIAIgBQATgDARACQAigPA0AHQA/AGgPAlQAyAAAAAQQAIAVgqAGQBEAHgVAiQgGAXhJAKQgdADgjABIgnAAQgMAFghADIgPABIgJAAgAqAAmQhAgCgvgRIgfgPIgIgEQhKgMgIgoQhCgLgFg6QgShDB+gmQgcguAygXQA+gmApAfQgPhJB1gcQBLgbBIA2QAqAjAcA3QAYADAbAbQAOAKADAjQAOAagjAhQg2Aog1gMQATAjgTAiQgZBEhcAPIgQADQgXAFgXACIgKAAgALjg4IgDAAIgLAAIgCAAIgFgBIgJgBIgZgDIgRgCIAAAAIgBAAIgBAAIgBAAIAAAAIgCgBIgKgCQgggJgOgRIgFgFIgBgCIgBgCQgGgIABgHIAAgDIACgEIACgFIABgCIABAAIgFAAIgCAAIgEAAIgFAAIgCAAIgHAAQgWgCgcgMQgYgPALgMQACgNAIgHIACgBQARgLASgDQAMgNALgJQALgKANgHQA5gZAuAKIAIABQApAIAQANQADAFgBAHIAFgBQAjgHAhARQAfAHgFAQIgCAEIACABQBNAQgIAbQAEAIgCAIIgCAFQgHAVgmAFIgEACIgEAEIgFAFQgNAKgiAEIgGACIgHADIgJADIgaAGQgVADgXABg");
	this.shape_71.setTransform(261.5,407.1);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#D2E077").s().p("AiTGxQgVgBglgBQAiAAAdgDQBKgLAFgXQAWghhEgIQAqgFgIgVQgBgRgyAAQAQgkg/gHQg0gHgiAPQgRgBgTACIgIACQgQADgQAHIAIgEIAkgUQAmhSBuAhQBvAhACAzQAeAGACAPQAAATgbAKQA1AJAbAcQAbAchJAHIhiALQgRACgTAAIgWgBgAuEAUQiHgigFiEQgDhcBqghQAFglAugYQA4gZAwAMQABg/BqgUQA5gKBCAKQAqAFAnAfQAcARARAdQAVAsAEAsQgcg4grgjQhIg1hKAaQh2AcAPBKQgpgfg+AlQgxAYAcAuQh+AlARBDQAFA7BDAKQAHAnBLANgANsg8IAFgFIADgEIAFgDQAmgFAHgUIABgGQADgIgFgHQAJgchNgQIgCAAIABgEQAFgQgegIQgigRgiAHIgFABQAAgGgDgFQgPgOgqgHIgIgBQgugKg5AYQgNAIgLAJQgLAJgMAOQAFgVARgUQALgHAMgBIASgCQAUgIAVgCQAQgDAQAAQAsgBAfAHQBMAMgBAdQAbABAZAKQAbAMgGAPQBEAMA1AiQA2AgirAaQgJgDgagEg");
	this.shape_72.setTransform(262.5,404.4);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#663300").s().p("ABSWJQAHkFAlj9QAPkcAhkeQAai2gGi1QAJithAjUIgIgLQhdkRikiXQhUhqgzhfQAXgBAggEIBQB5QARg5A2gzIANgBQg2A/gDBTQBnBqA9BdQCbDvAnC6QAiBjAQBhQAJA/ADBAQAxFQgTEgQAnFPAJFBIgEBNIgBALgAkmxiQhDiUgliRIAXgBQgBAJAHADIAAACQAoCMBEB5QABAFAEAFQgTAMgOAKIgFgNg");
	this.shape_73.setTransform(229.5,538);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#492513").s().p("AkZXDIADhOQgJlBgmlOQASkhgwlQQgDhAgKg+QAoi1BliYQBqjFCciPQBpiMBDiNIBXkYQALhMAZhMQAGgkAVgrIAMACQguB6gSCjQgGAhgHAgQgrC1hcCqQguBahxB2QjpEUglFhQBFLBAXLAg");
	this.shape_74.setTransform(297.3,531.1);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#CADC69").s().p("AlTG6IgGAAIgRgDIgTgBQgTgEgJgKQgNgTAYgLQACgCAFgBIgMAAQgTgBgQgEQgKgCgIgDQg3gTAZgbQAIgKAKgJIAIgFQAfgTA6gLIAIgCQAsgSApAFQAmgQA6AHQBGAHgRAnQA4AAAAASQAJAWguAGQBMAIgZAkQgGAZhSALQggADgnABIgsAAQgOAGgkADIgRAAIgKAAgAtqAEIgJgEQhUgNgIgrQhLgLgFg/QgUhICNgoQgfgxA3gZQBGgoAtAhQgQhPCDgeQBTgcBRA5QAwAlAfA8QAbADAeAdQAQALACAlQARAcgoAjQg9Arg6gNQAUAlgUAlQgdBJhnAQQgjAIghADIgXAAQhSAAhBglgAMsg8IgwgFQgKAAgJgDIgOgCQgsgLgQgZQgLgNAGgLIAFgKIgNABIgGAAQgfAAghgPQgcgQAMgNQADgRALgGQAUgMATgCQAMgOAPgMQANgKAPgIQA4gbA6ANQBdAOgNAlQAhgQAwASQAnAMgWAXQBiASgMAhQgFAdg0AFQgGATg6AHIgGACQguARg5AAIgQAAg");
	this.shape_75.setTransform(261.2,387);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#B6C461").s().p("AnXF/QghgBgZgJIgWACQghAEgWAAQhwADBUg8QANgKAUgMQgFgFAAgGIACgIQgIgLAMgHQgCgLAXgIQAHgJALgBQAGgBAJABIATgXQAQgUAlgHQAngIAkAbQg6ALgfATIgIAFQgKAJgIAKQgZAbA3ATQAIADAKACQAQAEATABIAMAAQgFABgCACQgYALANATQAJAKATAEIATABIARADIAGAAQAQABALgBQAkgDAOgGQgGAIgQAGQgWAIgXAGQgMADgSABIgNABIgSAAIgFAAQgZAAgXgFgAqdAdQghAFgMgHQgHgEAAgJIgWABQhCABgrgfQgdgUgVgmQBBAlBSAAIAXAAQAhgDAjgIQBngQAdhKQAUglgUglQA6ANA9grQAogjgRgcQgCglgQgLQgegdgbgDQAegGAdAGQAkAIAeAMQAdANAXAiQARAXAAAeQALAggRAjQDnCrmtgDQgWARgkAKQggAXgdgBQgaANgZAAQgMAAgMgEgAK9htIgMgCIgBgBQgWABgWgLIgUgFQgMgDgJgFQkrACCihPQgMgRAIgOQAAgOALgKQAQgQAUgFQAWgHAYgDQAVgCAVACQgTACgUAMQgLAGgDARQgMANAcAQQAhAPAfAAIAGAAIANgBIgFAKQgGALALANQAQAZAsALIAOACQAJADAKAAIAwAFIAQAAQA5AAAugRQgPASgVAJQgdAPgvgBIgPAAQAAAEgFABQgJAEgWgDQgJACgJAAQgKAAgLgDg");
	this.shape_76.setTransform(264,394.8);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#D2E077").s().p("AiyHQQgXgBgqgBQAnAAAggEQBSgLAGgYQAZgkhMgIQAugGgJgXQAAgRg4AAQARgnhGgIQg6gHgmAQQgpgEgsASIAxgaQArhXB7AiQB8AkACA2QAhAHAEAQQAAAUggALQA8AJAeAeQAeAehQAJIhvALQgSACgVAAIgagBgAv8AVQiXgkgFiNQgEhjB3gjQAFgoA0gZQA+gbA2AMQABhDB3gWQA/gLBLALQAuAGAsAhQAfASATAfQAYAvAEAvQgfg7gwgmQhRg5hTAdQiDAdAQBPQgtghhGAoQg3AZAfAyQiNAoAUBIQAFA+BLAMQAIApBUAOgAPQhMQA0gFAFgcQAMghhigTQAWgWgngNQgwgRghAPQANglhdgNQg6gNg4AaQgPAIgNALQgPALgMAOQACgVARgWIAIgHQALgJAQgHQAegOAigEQAzgEAtAEQBTALABAeQAlgFAsANQAkALAEASQBTAQA/AuQA9AtjsAlIhOADQA6gGAGgUg");
	this.shape_77.setTransform(263.7,384.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#A1BF37").s().p("AAoCkIgDgBIgMAFIgOAEQhnAehLhMQhPA4hZg6QgMgIgMgKIADgEIAEgGQBLhsCDAsQA3hWBhgEIATgXQATgVASgQQAVgUAUgNQBlhFBVBDIAGAFQAgAcAfAwQANBmhFBPQhNBOhYAAQgvAAgygXg");
	this.shape_78.setTransform(323.9,395.1);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#7AA234").s().p("AgKDMQgiABgfgJIgNgDQgRgGgQgIQgOgIgOgKQgNANgUAEQgoANgTgaQgNgIgHgLQhnAYhBhQIgDgDQgQgPgHgcQgEgRgBgPQAMAKAMAIQBYA7BQg4QBKBLBogdIAPgFIAMgEIACABQCOBBB3h4QBGhOgOhoQgCgPgFgOQBogbA+BBQBGBCgjBmQg4B3iJggQgkBVhjgUQhAApg7AAIgJAAg");
	this.shape_79.setTransform(334,404.5);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#B1D93D").s().p("AlmCpIAAgQQgBhjBggTQAjgKAYAKQAIhDA6gSIAQgEQAPgEAPAEIAKgQQATghAbgWQAUgQAWgLIAVgJQAVgHAXgDQAigFAmACIAfAEQBsARAoA9IABABIACADQASAaAJAeQAFAOACAPQgegwgggbIgGgFQhWhEhkBFQgVAOgUATQgTARgSAVIgTAVQhiAEg3BYQiDguhKBtIgFAGIgCAEIgBgGg");
	this.shape_80.setTransform(323.7,388.2);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#492513").s().p("AjsUBIADhNQgJlBgmlPQASkggwlPQgDhBgKg/QAoi1BliXQBqjGCciPQBpiMBDiNIAnh7QAQAIARAGQgqCahQCTQguBbhyB1QjoEUglFjQBFK/AXLAg");
	this.shape_81.setTransform(292.8,550.5);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#663300").s().p("ABSWJQAHkFAlj9QAPkcAhkeQAai2gGi1QAJithAjUIgIgLQg9ixhZh+QAiATAsAIIADAAIADADQCbDvAnC6QAiBjAQBhQAJA/ADBAQAxFQgTEgQAnFPAJFBIgEBNIgBALgAmO2HIAXgBQgBAJAHADIAAACQAbBcAnBUQgOAHgNAKQgphogbhmg");
	this.shape_82.setTransform(229.5,538);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#939E36").s().p("ACVC6IgbgIQgsgYgdg3QgbAZgdAHQgaALg0ACIgDAAQgsgIgjgTQgjgSgbgcQhIAshbgVQg9gNgXgfQAoAUA4gPQBBgSA0gfIAMgGQAwAvA2AKQBIAOBQg5QBjCCBzgsQB6gwgNiFQBqgmgDhJQAgAeADAlQAlB7hAAgQhBAggLALQgvB4hrAAQgbAAgfgHg");
	this.shape_83.setTransform(244.3,453.3);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#B3BE35").s().p("AA4DTQhQA4hIgNQg2gLgwgwIgMAIQg0AfhBARQg4APgogTQgKgFgJgHQgVgRgQgcQgwhaAKhHQAKhFA1g5QASgTAYgOQAPgJAQgGQAkgPAugGIAPgCQAjgCAeAGQAvAKAjAhQAFgrANgdIADgFQAJgTAMgNQA9g8BUAAQBFAAArAyQBQhjBDBdQAUgvA5gLQA5gLAqAcIADACIABAHQABAPAEARQAHAbAQAQIADADIgBAGQgKBAgkAUQgbAPgGgCQAfAsAJAkQACALAAAJQADBJhqAmQANCHh6AvQgdAMgcAAQhTAAhKhhg");
	this.shape_84.setTransform(239,433.6);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#C5D644").s().p("Am9EhQgZgbgZg/QgXhMAIg6QAKhTBMg7QAMgLAMgIQANgKAOgHQBHgoBeAVIAKADIABgFQAJh9B3gkQBhgdBEBIQAig+AyAMQApAHAYAqQAIgUAPABQgDgEAYgNQAGgDAzgCIAAABIAJgCQAVgDAVADQAxAIAvAoQAMAGAIAKIABAPIgDgCQgrgcg4ALQg5ALgVAvQhChdhRBjQgrgyhEAAQhVAAg8A8QgNANgJATIgCAFQgNAdgFArQgjghgvgKQgegGgjACIgQACQguAGgkAPQgQAGgOAJQgYAOgSATQg1A4gLBGQgKBHAxBaQAPAcAWARIgEABQgLAAgOgQg");
	this.shape_85.setTransform(236.5,426.7);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#B6C461").s().p("AlNEeIAJgDIABAAIAAAFIgKgCgAoHCBQghAFgMgIQgHgDABgJIgXABQhCABgrggQgcgUgWgmQBCAkBSABIAWgBQAhgDAkgIQBngPAchKQAVgkgVglQA6ANA+grQAngjgRgdQgCglgQgLQgegdgbgDQAegFAdAFQAlAJAdAMQAdAMAYAiQAQAYAAAeQALAggRAjQDnCqmtgEQgWASgjAKQghAYgdgCQgaANgZAAQgMAAgMgDgAJohwQgMgRAIgOQAAgOALgLQAQgPAUgGQAXgGAYgEQAVgCAUACQgTACgUANQgKAGgEAQQgMANAcARQAXAJAUAEQgXALgUAQQgaAWgUAhQi2gKCGhBg");
	this.shape_86.setTransform(249,384.9);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#CADC69").s().p("AtqDNIgJgFQhUgOgIgqQhLgMgFg+QgUhHCNgoQgfgyA3gZQBGgoAtAhQgQhPCDgdQBTgdBRA5QAwAmAfA7QAbADAeAdQAQALACAlQARAcgoAjQg9Arg6gNQAUAlgUAkQgdBLhnAPQgjAIghADIgXABQhSgBhBgkgAMfApIgfgEQgmgCgiAFQgYADgUAHIgVAJQgVgEgWgJQgcgRAMgNQADgQALgFQAUgNATgCQAMgOAPgMQANgKAPgIQA4gaA6ANQBdANgNAlQAhgPAwARQAnANgWAVQBiATgMAhQgFAcg0AFQgGASgwAHQgog9hsgRg");
	this.shape_87.setTransform(261.2,367);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#D2E077").s().p("Av8DvQiXglgFiNQgEhiB3gjQAFgoA0gZQA+gbA2AMQABhDB3gWQA/gLBLALQAuAGAsAhQAfASATAfQAYAvAEAvQgfg7gwgmQhRg5hTAdQiDAdAQBPQgtghhGAoQg3AZAfAxQiNAoAUBIQAFA+BLAMQAIAqBUAOgAOaCmQAwgHAGgSQA0gFAFgcQAMghhigTQAWgWgngNQgwgRghAPQANgkhdgNQg6gNg4AaQgPAIgNAJQgPAMgMAOQACgVARgVIAIgHQALgJAQgHQAegOAigEQAzgEAtAEQBTALABAeQAlgFAsANQAkAKAEASQBTAQA/AuQA9AtjsAlIhDADg");
	this.shape_88.setTransform(263.7,362.3);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#939E36").s().p("AC6DPIgigIQg2gbglg9QgiAbglAIQggAMhBACQgegEgZgIIgvgRIgCgBQgrgUgigfQhbAxhygYQhNgOgdgiQAzAWBGgRQBSgUBBgiQBCAoA9ANIAQAEQBbAPBlg/QB7CQCRgxQCZg1gQiVQCFgqgDhSQAnAiAFApQAuCKhRAjQhRAkgOAMQg7CHiGAAQgiAAgogJg");
	this.shape_89.setTransform(239.4,426.9);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#C5D644").s().p("AowFCQgfgegfhHQgdhUAKhAQANhdBfhCQAPgMAPgKQAQgLASgIQBagsB1AYIAGAAQAHgBABgCQAMiLCVgpQB6ggBVBRQArhFA+ANQA0AIAeAvQAKgXAUACQgEgGAegOQAHgDBAgDIALAAQAbgDAaADQA+AIA6AtQAQAHAKALIABARIgEgCQg3gfhFAMQhIAMgaA0QhThnhlBuQg2g4hWAAQhrAAhMBDQgPAOgMAVIgDAGQgQAggGAxQgsglg7gLIgTgDQgigDgxADQg5AHgtAQQgVAIgSAJQgeAQgWAWQhDA+gNBOQgNBQA9BjQAUAgAbATIgFABQgNAAgTgSg");
	this.shape_90.setTransform(229.6,397.3);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#B3BE35").s().p("ABHDrQhlA/hbgPIgQgDQg9gOhCgoQhBAjhSATQhGARgzgWQgMgFgLgHQgbgTgTggQg9hkAMhPQANhOBDg/QAXgWAegPQASgKAUgHQAtgRA6gGQAwgEAiADIATADQA7AMAsAkQAGgwARggIADgGQALgVAQgOQBMhEBqAAQBWAAA2A4QBlhuBUBoQAZg1BIgMQBFgMA4AfIADACIABAIQACAQAEATQAIAYAOAQIAIAIIADAEIgBAHQgNBHgtAXQgiAQgIgCQAoAxALAoQADANAAAKQADBRiFArQAQCWiZA1QglAMgjAAQhoAAhchsg");
	this.shape_91.setTransform(232.7,405);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#663300").s().p("ACfPvQASk9Aqk/QAhjKgHjLQAKjAhQjtIgLgNQhLjFhwiMIABABIAuARQAYAHAbAFQDKEOAyDQQApBuAUBsIAAABIABAEIAOBwIACAbIAAABQA6FogUE2IAAABIABAmIAFAkIAvIYIAEBbIAAANIgBBDIgBARIABAAIgCAqImJAMQAIkkAvkagAnz4rIABAAIAbgBIAHAOIABACQAiBnAwBeQgRAIgQALQg0h0ghhzg");
	this.shape_92.setTransform(220.7,521.4);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#492513").s().p("AkGWNIgbgqIgBAAIABgRIABhDIgBgNIgDhbIgwoYIgEgkIgBgmIAAgBQAUk2g7lnIAAgBIgCgbIgNhxIgBgEIAAgBQAyjJB+ipQCBjXC8icIAcgdQBxiIBMiKIAXg0IAehUIAbgFIAAADIALAjQguCLhPCGQgRAegVAfQg1BNhhBeIgkAmIgbAcQjyEUg2FWQgCA1AAA1QBRLpAbLqIgXARg");
	this.shape_93.setTransform(299.6,536.2);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#7AA234").s().p("AgNDkQgvAAgqgKIgcgJQgUgHgTgKQgRAAgVgFQghAPgYgKQgjAGgQgXQglAAgcgMQhgAKhAhIIgDgEIgIgIQgOgQgHgYQgFgTgBgQQAOALAPAJQBWA0BPglQBJAyBdggQAwAhBCgPIADgBIAVgGIAKAEIE7g7IAFgEIABgBQBXhXgRh0QgDgRgFgQQCCgeBOBIQBYBKgtBzQhGCEirgjQguBeh8gWQhRAuhJAAIgMAAg");
	this.shape_94.setTransform(352.1,372.5);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#B6C461").s().p("AmWE9IgHADIgGAAIANgDgAqMCRQgpAGgPgJIgBAAIgHgOIgcABIAAAAQhUACg1gkQgkgXgbgqQBSApBnAAIAcAAQAqgDAsgJQCCgSAjhSQAagpgagpQBKAPBNgwQAxgngVggQgDgpgUgNQgmggghgDQAlgHAlAHQAtAJAmAOQAkANAdAmQAVAbAAAhQAOAkgVAnQEhC+oZgEQgdATgsALQgoAbglgCQghAPggAAQgPAAgPgEgANBgoQjjgLCohJQgPgTAKgQQAAgPAOgMQAUgRAZgGQAcgIAegDQAagDAaADIAAAAIACgDIgBADIgJABQgUAEgWAMQgIAFgEAIIgDAGIgBAFQgPAOAjATQAPAFANAEIAZAFQgMAGgMAGIgMAIIgRAKQgVAQgRAUQgLAMgJAOIgBAAg");
	this.shape_95.setTransform(245.2,350.5);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#A1BF37").s().p("AhbCzQhcAghKgyQhOAlhWg0QgPgJgPgLIADgFIAEgFIACgBIAKgNQBJhXB0AYQA/g9BiAGQAngvA/gJQAdgeAdgWQAZgWAagPQB+hNBsBLIAFAEIABAAIACABIBOBVQARBzhXBYIgBABIgFAEIk8A7IgLgEIgUAGIgDABQgVAEgSAAQgpAAgigWg");
	this.shape_96.setTransform(339.3,361.3);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#B1D93D").s().p("AnBC8IgBgRQgBhvB4gWQAdgHAWAGQASguAygJQAKggAngIIA2gNIAFgIIABAAQAJgNALgNQARgTAVgQIAQgLIAMgHQAMgHAMgFIABAAIATgIIAHgCIAPgEIATgEIAWgDQAQgCARgBIAqgBIALABIAHAAIADABIAbADIANACQB9ATAyA/IABAAIADAEIADADQAXAeALAhQAGAQADARIhOhVIgCgBIAAAAIgFgEQhshLh+BNQgaAOgaAWQgcAXgdAeQhAAHgmAvQhjgFg/A9Qh0gXhJBXIgKANIgCABIgDAFIgDAFIgBgIg");
	this.shape_97.setTransform(339.1,354.3);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#CADC69").s().p("AxKDlIgegHIASACQgogHgbgKQgpgSgHgcQhegNgHhGQgYhPCxgtQgog3BGgcQBXgtA5AlQgUhYClghQBoggBlBAQA9AqAnBCQAhAEAmAgQAUAMADApQAVAfgxAnQhNAwhKgOQAaApgaApQgjBTiCARQgsAJgqADIgcABQhngBhSgogASjCCIgBAAQgyg/h9gTIgOgCIgbgEIgCAAIgHAAIgLgBIgqAAQgRABgRADIgVADIgTAEIgQAEIgGACIgUAIIAAAAIgZgGQgOgEgPgFQgjgSAPgPIACgFIACgGQAEgHAIgEQAWgNAUgEIAJgBIACgCQAPgQASgLQAPgLASgIQBIgeBIAOQBzAPgOAoQAqgQA7ATQAxAOgbAYQB1AUgJAiQgLAig4AHIgIAEQgKAQgxAHIgIgCg");
	this.shape_98.setTransform(260.6,330.6);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#D2E077").s().p("AxFETIh7gIQi9gqgHidQgEhuCVgmQAHgtBAgcQBOgfBFAOQAAhLCWgYQBPgMBeAMQA6AGA4AlQAmAVAYAiQAeA1AFA0QgnhCg8gqQhlhAhpAgQilAhAVBYQg5glhXAtQhGAcAnA2QixAtAZBQQAHBGBdANQAHAdAqARQAaALApAGgAVdCfQAPgIgDgIQAHgJgHgMQAIgFAAgJQAFAKgIAKIAAAEQAkAQgVANQARAGglAEQAGgGgSgGgAVsBkIADgCIgHgLQgJgTgrgMQgOgOgpgIIgFgBQAAgSgngJQgUgEgSgBQgTgLgpABQgFgPgdgKQgfgJgwgEQgWgCgWAAQgqABgoAQIgPAGQgRAIgNAKIgFADQgMALgIANQAKgRASgQIAWgOIAWgJQAngPAqgCQAUAAAUABQAtACAgAGQAhAIAHANQAsADAUASQAOAAANABQAmAFAEAOIAOADQArAKANARQAhAJAKANQAQARgHAMQACAFAAAFIgFgIg");
	this.shape_99.setTransform(257.2,325.4);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#939E36").s().p("ADgDkIgpgJQhCgdgshEQgpAfgtAIQgmANhOADQgkgFgggJIg5gUQg1gWgoghQhuA1iIgaQhdgQgjglQA8AXBVgSQBjgVBPgnQBQAsBHAPIAUAEQBuARB5hGQCVCgCug3QC4g6gTilQCggugEhaQAwAlAFAtQA4CYhhAnQhjAogPANQhICVihAAQgpAAgwgKg");
	this.shape_100.setTransform(234.5,400.6);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#B3BE35").s().p("ABVECQh5BGhugRIgUgDQhHgQhQgsQhPAnhjAVQhVASg8gXQgPgGgNgJQghgVgXgiQhJhvAPhXQAQhWBQhGQAbgXAkgSQAWgKAYgIQA3gSBFgIQA6gDApADIAXADQBHAMA1ApQAHg1AUgkIAEgGQAOgYASgPQBchKCAAAQBoAABAA9QB6h5BlByQAfg6BWgNIADgBIBOAAQAlAFAgARIAEACIABAIQACATAGAVQAJAcATASIAHAHIAEADIgCAIQgPBPg2AZQgoARgKgCQAwA3AMAsQAEAOAAALQAEBaigAuQATCmi4A6QgtAOgqAAQh9AAhvh3g");
	this.shape_101.setTransform(226.4,376.5);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#C5D644").s().p("AqiFkQgmgiglhNQgjheAMhHQAPhmB0hJQARgNASgLQAUgMAVgJQBsgwCNAZQAQAAABgCQAPiaCzgtQCTgjBnBZQAzhNBMAPQA+AJAkAzQAMgYAXABQgEgFAkgQQAJgEBNgCIANgBQAhgEAfAEQBKAJBHAxQASAIANAMIAAATIgEgCQgggRglgFIhOAAIgDABQhWANgfA6Qhlhyh6B5QhAg9hoAAQiAAAhcBKQgSAPgOAYIgEAGQgUAkgHA1Qg1gphHgMIgXgDQgpgDg6ADQhFAIg3ASQgYAIgWAKQgkASgbAXQhQBFgQBXQgPBXBJBvQAXAiAhAVIgGABQgQAAgWgTg");
	this.shape_102.setTransform(222.6,367.9);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#663300").s().p("AC/RXQAWldAylgQAnjggIjgQAMjUhgkEIgMgPQhbjaiIibIA4AUQAeAJAhAEQDzEqA8DmQAyB5AYB4IAAABIACAKIAOBtIAEArIADARIAxH8IgFDGIgCAbIAAACIADAoIABACIACAMIALBUQAqFPALFEIAAACIgDBJIgBASIAAABIgBAVInZANQALlCA4k3gApZ7OIABAAIAggBIAJAOIABADQAoBxA7BoQgVAJgUAMQg+iAgnh+g");
	this.shape_103.setTransform(212,504.8);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#492513").s().p("AkoYkIg6gVIgBAAIABgSIAEhKIAAgCQgMlEgqlPIgLhTIgCgMIAAgDIgEgnIAAgCIACgcIAFjGIgxn7IgDgRIgDgrIgPhuIgCgKIAAgBQA8jeCYi6QCXjnDdiqIAhgdQCHiTBdiUIAfg5IAjhdIAXgYIAEgJQARAPASAMQg2CahbCUQgUAhgZAjQg5BVhyBnIgsApIghAeQkqEphLFzQgJA6gEA8QBjNBAjNCIgLAig");
	this.shape_104.setTransform(307.4,520.7);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#7AA234").s().p("AgQD7Qg7ABg2gOQgXgFgUgJQgXgIgWgMQgUAJgcAAQg0AQgdgWQgcgDgPgTQg8AIgxgOQhYgDhAhBIgDgEIgIgGQgTgSgJgdQgFgVgCgSQASAMASAKQBTAuBNgSQBJAYBQgiQBaBDB+gbIABAAIAIgCIAagHIADABIALAEIALAEQDKBBCriNQBqhggViAQgDgSgIgSQCdghBeBQQBqBRg1B+QhVCSjOgnQg3BpiWgZQhhA0haAAIgNgBg");
	this.shape_105.setTransform(370.1,340.5);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#A1BF37").s().p("ABSDSIgLgEIgMgEIgDgBIgaAHIgIACIgBAAQh8AchahDQhQAihKgZQhNAShTguQgSgKgSgMIAEgFIAHgHIAKgMIC2hMQBIgjBhAOQBFhRB1gHQApgnAmgcQAfgYAfgQQCYhVCBBTQAeAUAbAaIAvA1QAUB+hpBhQh1BgiEAAQg9AAhAgUg");
	this.shape_106.setTransform(354.7,329);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#B1D93D").s().p("AodDQIgBgTQgBh7CRgXQAXgGASADQAegaAoAAQAMg9BIgQQAwgKATABIAKgOIABAAIALgPQAOgQAQgOIAdgXIAGgEIAGgEIACgBIAlgTIANgFIAAAAQAPgHAQgEQAdgJAigDIAFgBIAIgBIBGgDIAZABIAFAAIANABIAKABIAMACIAMABIAEAAIAKACIC7BHIAQAQIACAAIAFAHIAEAEQAcAhANAkQAIASADASIgvg0QgbgagdgVQiChSiXBUQggARgfAYQgmAcgoAlQh2AHhEBTQhigQhHAlIi3BMIgKALIgHAIIgDAFIgBgIg");
	this.shape_107.setTransform(354.5,320.4);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#B6C461").s().p("AsRD/QgxAGgSgJIgCgBIgJgPIggACIgBAAQhkABhBgoQgrgYghgvQBjAtB8ABIAigBQAzgEA1gKQCbgTArhbQAfgtgfgtQBZAQBcg1QA8grgZgjQgEgugYgNQgugkgogDQAtgHAsAHQA3AKAuAPQAqAPAkAqQAZAdAAAlQARAngaAsQFdDRqIgEQghAVg2AMQgxAegsgCQgoAQglAAQgTAAgSgEgAPrAxQkQgMDJhPQgSgVAMgRQAAgRARgNQAXgUAfgGQAigIAkgFQAfgCAgACIgCABQgcACgdAPIgBABQgQAHgEAUIgBABQgHAHAEAHIABADQAGAIAUAKIAFACIABAAIACABQAeAJAbAEIgNAGIglATIgCABIgGAEIgGAEIgdAWQgQAOgOAQIgLAOIgBAAg");
	this.shape_108.setTransform(241.5,306.7);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#CADC69").s().p("A0rD8IgmgHIAZABQg5gIgigPQgpgSgHgcQhxgOgIhNQgehYDWgxQgwg9BUgfQBpgxBFApQgZhiDHgkQB9gjB6BGQBJAvAuBJQApADAtAkQAYANAEAuQAZAig7ArQhcA1hZgQQAfAugfAtQgrBbibATQg2AKgyAEIgiABQh8gBhkgtgAWSCMIgBgBIgRgQIi6hGIgKgCIgEAAIgMgCIgMgBIgKgBIgNgBIgFgBIgZAAIhHADIgHABIgGABQghADgeAJQgQAEgOAGIgBAAIgNAGIANgGQgcgEgegKIgCAAIAAgBIgFgBQgUgKgGgJIgCgCQgEgHAIgHIABgBQAEgUAPgGIABgBQAdgPAcgDIACAAIABAAIABgCQAUgRAWgOQASgLAWgKQBVggBYAQQCKAQgRAtQAygRBHAUQAcAHAHAKIgCAEIAEAAQAEAKgPALQCPAXgNAmQgLAKgbAFQABAQgdAKIgSADQgCAEgGADQgQAQg5AHIgIgGg");
	this.shape_109.setTransform(260,294.3);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#D2E077").s().p("A1OEvIiRgJQjkgtgHiuQgFh5CzgqQAIgyBOgfQBeghBSAPQAAhTC1gbQBggNBwANQBGAIBDAoQAvAXAcAmQAkA6AGA6QguhJhJgvQh6hGh9AjQjHAkAZBiQhFgphpAxQhUAfAwA8QjWAxAeBZQAIBNBxAOQAHAcApASQAiAQA5AHgAXvCzIAFgEIAMgDQAdgLgBgQQAbgFALgKQANgmiPgXQAOgMgDgKIgEAAIACgDQgHgLgcgHQhHgUgyARQARgsiKgQQhYgQhVAgQgWAKgSALQgWANgUARIgBACIgBAAIABAAQAGgWAVgVIAFgEQAPgMAUgIIATgHQAugSAzgDQAbgBAaABQA1ABApAHQAjAHASALQA5AHAKAUQAWAAAYACQAoAFAVANIAGABQA1AMAKATQAtAKAaAOQAoAUATARQARAMAJAMQARANgOAMQAAANgtANQgWAHhQAGQgUgGgvgGg");
	this.shape_110.setTransform(259.7,288.5);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#663300").s().p("ACRd0QANlgBBlUQAal+A6mCQAuj1gKj0QAPjohxkdIgOgRQhrjuieipQA+AZBNAMIAFAAIAEAEQETFBBGD8QA6CFAcCCQASBVAEBVQBXHGghGEQBEHBAQGxIgHBoIgBAPgArA9yIAngBQAAAMAMAFIAAACQAvB8BFBxQgZAKgXAOQhIiNgviKg");
	this.shape_111.setTransform(203.3,488.2);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#492513").s().p("Amja9IAHhoQgQmxhEnCQAhmEhXnEQgEhXgShUQBHj0CyjMQCxj8EDi6IAdgUQC6i9B3i+IBDimQAcAMAfAHQhLDQiNDGQhKBuiqCLIgnAfQmcFzg/HeQB6OzAoO0g");
	this.shape_112.setTransform(315.1,505);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#939E36").s().p("AEGD5IgwgJQhNghgzhKQgwAig1AJQgtAOhbADIgGAAQhNgLg/gZQg+gZgvgkQiAA6iggcQhsgSgpgpQBHAaBjgUQBzgXBcgqIAUgJQBXBABeAOQCAASCOhMQCuCuDLg7QDYhAgWi0QC7gzgFhiQA4AoAGAyQBCCmhyArQhzArgTAOQhTCji9AAQgwAAg4gLg");
	this.shape_113.setTransform(229.6,374.2);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#A1BF37").s().p("ABGDdIgFgBQgXAHgXAEQi3AoiEhlQhEAkhJABQhMAAhQgpQgVgLgVgNIAEgFIAIgIQBMhVBugPQBQgLBhAZQBih1CsgFQAzgvAwgiQAkgaAlgSQCxhdCYBbIALAGQA4AlA2BBQAYCLh7BqQiJBpiaAAQhUAAhYgfg");
	this.shape_114.setTransform(370.2,295.9);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#7AA234").s().p("AgTETQhIAAhBgQQgfgHgcgMQgZgKgZgNQgXARgjAFQhHARgigjQgXgKgMgPQhUAPhFgPQhSgRg+g6IgEgEQgdgVgNglQgGgXgCgUQAUANAVALQBRApBMAAQBIgBBFgkQCDBlC4goQAXgEAYgHIAEABQD8BYDSiiQB7hpgYiMQgEgUgIgUQC3gkBuBXQB8BZg/CLQhjCfjxgqQhAByivgbQhyA4hoAAIgQAAg");
	this.shape_115.setTransform(388.1,308.5);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#B3BE35").s().p("ABkEcQiPBMh/gSQhfgOhWhBIgUAKQhdAqhyAYQhkAUhGgaQgSgGgPgKQgmgXgcgmQhVh4ARhgQATheBehMQAfgaArgTQAZgMAdgJQA/gTBRgIIAcgDQA9gDA2AJQBTANA+AtQAIg7AXgnIAFgHQAQgZAWgRQBrhRCWAAQB5AABMBDQCOiFB2B9QAkg/BlgPQBkgPBLAmIAFADQAAAFACAEQACAUAGAXQANAlAdAVIAEAEIgCAIQgRBXhAAbQgvATgMgCQA4A7APAxQAFAPAAAMQAFBii8AzQAXC1jYBAQg0APgyAAQiSAAiBiCg");
	this.shape_116.setTransform(220.1,347.7);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#C5D644").s().p("AsUGGQgtglgqhVQgqhmAOhOQAShwCHhQQAUgOAVgMQAXgNAZgKQB/g1ClAcIATAEIABgHQARioDSgxQCsgmB3BhQA8hUBZARQBIAJAqA4QAOgaAcABQgFgGAqgSQAKgEBagCIAAABIAPgCQAngEAlAEQBWAKBTA2QAWAIAOAOIABAUIgFgCQhMgmhkAPQhlAOgkBAQh1h9iPCEQhLhDh5AAQiXAAhrBSQgVAQgQAaIgFAHQgXAngJA6Qg+gshTgOQg1gIg9ADIgcACQhRAIhAAUQgcAJgaALQgqATggAaQheBLgSBfQgSBgBWB5QAbAmAmAXIgHAAQgSAAgagUg");
	this.shape_117.setTransform(215.7,338.4);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#B1D93D").s().p("Ap5DjIgBgUQgBiHCpgZQARgEAPgBQApgEAgAJQAOhbBngYIAbgFQAcgGAaAGIAQgWQAjgrAvgfQAkgVAngPQA0gTA/gHQA8gHBEAEQAdACAaADQC+AXBHBSIACABIADAEQAgAkAQAnQAJAUAEAUQg2hBg4glIgLgGQiYhbixBdQglASgkAaQgwAigzAuQisAFhiB2QhhgZhQALQhuAPhMBVIgIAIIgEAFQgBgEAAgFg");
	this.shape_118.setTransform(369.9,286.5);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#B6C461").s().p("ApOGBIASgDIACAAIgBAGIgTgDgAuWCuQg6AGgVgKQgMgEAAgNIgnACQh2ABhLgrQgzgbgmgzQB0AxCRABIAogBQA7gEA+gLQC2gVAyhjQAkgxgkgyQBoASBsg6QBGgwgegmQgFgygcgPQg1gmgvgEQA1gIA0AIQBAALA1AQQAyARAqAuQAcAfAAApQAVArgfAvQGYDlr1gEQgnAXg/ANQg5Ahg0gCQguARgsAAQgWAAgVgEgARBiXQgUgXANgTQABgTATgOQAbgVAkgHQAogJAqgFQAlgCAlACQgiADgjARQgUAIgEAWQgWASAyAWQAnAMAkAFQgoAPgjAWQgwAegiAsQlAgODrhXg");
	this.shape_119.setTransform(237.8,282.1);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#CADC69").s().p("A4LEUQgHgEgIgCQiTgTgQg5QiEgQgJhUQgjhgD5g2Qg3hCBigiQB7g2BQAtQgdhrDogoQCTgmCOBNQBWAzA2BQQAvAEA2AmQAcAPAEAyQAeAlhGAwQhsA6hogSQAkAygkAxQgyBki1AVQg/ALg7AEIgnABQiSgBh0gxgAWEA4QgagEgcgCQhEgDg8AHQg/AGg1ATQgkgFgngMQgygWAWgSQAFgWATgHQAjgRAjgDQAngjA6gYQBigkBoASQCjASgWAyQA7gVBUAYQBFAQgnAeQCsAZgVAsQgIAmhdAHQgJAYhVAKQhIhTi+gWg");
	this.shape_120.setTransform(259.4,258);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#D2E077").s().p("A8NFCQkKgygJi+QgGiFDRguQAKg2BbgiQBuglBgARQAAhaDTgeQBwgOCEAOQBSAIBOAsQA2AZAiAqQAqA/AHBAQg2hQhWgzQiOhNiTAmQjoAoAdBrQhQgth7A2QhiAiA3BBQj5A2AjBhQAJBUCEAQQAQA5CTATgAZeDgQBVgKAJgYQBdgHAIgmQAVgsisgZQAngfhFgQQhUgYg7AVQAWgxijgSQhogShiAkQg6AXgnAjQAEgcAcgdQAZgTAlgLQA2gUA8gFQBbgGBPAGQCSAPABAoQBDgHBNASQBBANAFAZQCUAWBvA9QBrA9mfAxIh4AEg");
	this.shape_121.setTransform(263.8,251.7);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#90A034").s().p("As+D6QAPADA7ghQBCgkAbhrQAFgUADgXQAJg6gLgtIgDgLIAHANQAbA4ASA6QAHAWAEAWQAQBkg3BUQAqAOAugFQAngFApgSIAegOQB3gFA1hRQBEBKCphBQBZCwkYAvQgngLgnALQgVAEgSAGQhrAUhOgiIgRACQgrAEgjgMQglgMgagcQg8AUgBBAQgShQhHhhgADFBdQA1guAbg7QANgeAHgiQBkAiBggfQBPgZBNhGQBchcgaimQB6BigGCWQglCniNA8QhdAahVgaQADAcgSAUQgogDhsBfQgkAggZAAQgyAAgEiAg");
	this.shape_122.setTransform(412.7,323.8);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#939E36").s().p("AE3GoQgfgFgggIIg9gQIgWgOQhSg2g5hrQgpAngvATQgSAIgTAFQgmAOg8AHQglAFgsABQi9gjh6h9QiiBgjIguQiIgdgzhEQBZArB8ghQChgrB9hQQCoClDCgnQA4gLA6gdQAsgVAtgfQCcDOCwAHQBEADBIgbIAcgMQCxhRAhitQALg6gGhFIAAgKIAZgJQAqgRAigUQBgg5AYhQQAIgegBggQANAMALANQAfAlANApQAHAVACAYQgmAHggANQhHAbBBgVIBMgaQFiC3knBqQjNBKg6AsQgbATADANQhpEMjrAAQggAAgjgEg");
	this.shape_123.setTransform(252.2,414);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#B3BE35").s().p("AkUQEQiwgIidjOQgsAggsAVQg6Adg5ALQjBAnipinQh9BRihArQh8AihZgrQgWgLgTgPQgwglgihAQhrjGAWidQAQhuA/heQAOgVAQgUQAPgSARgSQB2h9DfgcQDggdCICAQAVioBIhIQBLhKBbghQBKgbBUAAQBTAABBAhQA4AbArAyQAWgaAVgUQBchXBTAdQA4AUA0BIQASgpAegcIAIgJQAbgWAkgOQAXgJAcgFQAtgJApADQBJAEA9AoQARAMAOAPQgMg/g7geIgUgQQgkgdgmgUQgYgMgZgJQhZghhdARQAhi+CwgoIAWgIQBQgYBqAiIAGgTQAMggAOgcQBUioC0gTQBmgDBVAjQAlAQAhAWQAYAQAXAUIAYgYQAXgXAYgUQD/jPFCCmQDJANAnCvQAZCRh5BLQAaCmhcBcQhMBGhQAZQhgAfhkgiQgHAigNAeQgaA8g2AuQhOC/iVhzQipBBhEhKQg1BRh3AFIgeAPQgpARgmAFQguAFgrgOQA3hTgQhkQgEgWgHgWQgSg7gbg4IgHgNIADAMQALAsgJA7QgDAXgFAUQgaBqhDAkQg7AhgPgDQBHBhASBQQAFAYABAWQACAhgJAdQgYBRhgA5QghATgrARIgZAKIABAKQAFBEgLA6QggCvixBRIgcALQhAAZg+AAIgOAAgA0NhqQAaACAYADIANADIAAAFQgggIgfgFg");
	this.shape_124.setTransform(305.7,335.7);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#C5D644").s().p("A5jPnQg3g9g3iLQg0ioASiAQATiTBthxQAfhaBxhCQAUgPAVgLQAXgOAZgJQB/g0ClAbIATADIABgGQAKhiBNg6QBAhfB/guIAbgJQA/gSA5AAQCCAABkBhIANACIALACQBKh7BoAaQBZAPA1BYIAFAAQASgnAfACQg8hkAUhqQAJjEDgg2IAcgGQBTgOBLAYQALgcANgaQBciyC6gYQCxgkB7CGQDIjUD+AoQEDATCPDbQlCinj+DQQgYATgYAXIgYAZQgWgUgZgRQghgWglgPQhVgjhmADQi0AShUCoQgOAcgLAhIgHATQhqgjhQAZIgWAIQiwAogiC+QBegSBZAhQAZAJAYANQAmAUAlAcIATARQA8AeAMA+QgOgPgSgLQg9gohJgFQgpgCgtAIQgbAFgYAJQgkAOgbAXIgJAIQgeAdgSApQg0hJg3gUQhTgdhcBXQgVAUgVAbQgsgzg3gbQhCghhSAAQhVAAhJAbQhcAhhKBJQhJBJgUCpQiJiCjfAdQjgAdh2B9QgRASgOASQgRAUgNAVQg/BfgQBuQgXCcBrDGQAjBAAvAlIgIACQgXAAghgjgAw/BHIABgGIgOgCQgYgEgZgCQAeAFAgAJg");
	this.shape_125.setTransform(291.4,319.3);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#663300").s().p("ACRd0QANlgBBlUQAal+A6mCQAuj1gKj0QALiyg/jSQA8gHAmgOQATgFATgIQATAxANAuQA6CFAcCCQASBVAEBVQBXHGghGEQBEHBAQGxIgHBoIgBAPgArA9yIAngBQAAAMAMAFIAAACQAvB8BFBxQgZAKgXAOQhIiNgviKg");
	this.shape_126.setTransform(203.3,488.2);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#492513").s().p("AlfYpIAHhoQgQmxhEnCQAhmEhXnEQgEhXgShUQAniGBHh5IAVANIA9AQQAhAJAfAEQg/CYgWCkQB6OzAoO0gAE70mIgGAGIgeAKQgDAAAngQgAFN20QAxg6Asg6QAjAMAsgEQglA9grA8QgUAfgdAhQgNgpgegkg");
	this.shape_127.setTransform(308.3,519.8);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#B6C461").s().p("AB0GBIASgDIACAAIgBAGIgTgDgAjTCuQg6AGgVgKQgMgEAAgNIgnACQh2ABhLgrQgzgbgmgzQB0AxCRABIAogBQA7gEA+gLQC2gVAxhjQAkgxgkgyQBoASBsg6QBFgwgdgmQgFgygcgPQg1gmgvgEQA0gIA0AIQBAALA2AQQAxARAqAuQAdAfAAApQAUArgeAvQDvCGifA2Qg5AAg/ASIgcAJQhvALiqgBQgoAXg/ANQg3Ahg0gCQgvARgsAAQgVAAgVgEg");
	this.shape_128.setTransform(167.1,282.1);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#CADC69").s().p("AkmEUQgIgEgIgCQiTgTgQg5QiEgQgJhUQgjhgD6g2Qg4hCBjgiQB6g2BQAtQgchrDngoQCSgmCPBNQBVAzA3BQQAvAEA1AmQAcAPAFAyQAdAlhFAwQhsA6hogSQAkAygkAxQgyBki2AVQg+ALg7AEIgnABQiRgBh0gxg");
	this.shape_129.setTransform(134.2,258);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#D2E077").s().p("AljFCQkKgygJi+QgGiFDRguQAKg2BbgiQBuglBgARQAAhaDSgeQBwgOCEAOQBSAIBOAsQA2AZAiAqQAqA/AHBAQg2hQhWgzQiOhNiTAmQjnAoAdBrQhQgth7A2QhiAiA3BBQj5A2AjBhQAJBUCEAQQAQA5CTATg");
	this.shape_130.setTransform(118.8,251.7);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#663300").s().p("ACRd0QANlgBBlUQAal+A6mCQAuj1gKj0QALiyg/jSQA8gHAmgOQATgFATgIQATAxANAuQAVAvARAvIASj3QAhA+ApAsIAPCZQgjBMgYBRQASBVAEBVQBXHGghGEQBEHBAQGxIgHBoIgBAPgArA9yIAngBQAAAMAMAFIAAACQAvB8BFBxQgZAKgXAOQhIiNgviKg");
	this.shape_131.setTransform(203.3,488.2);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#939E36").s().p("AE3GoQgfgFgggIIg9gQIgWgOQgigXgfggQgpgsghg+QgpAngvATQgSAIgTAFQgmAOg8AHQglAFgsABQi9gjh6h9QiiBgjIguQiIgdgzhEQBZArB8ghQChgrB9hQQCoClDCgnQA4gLA6gdQAsgVAtgfQCcDOCwAHQBEADBIgbIAcgMQCxhRAhitQALg6gGhFIAAgKIAZgJQAqgRAigUQBgg5AYhQQAIgegBggQANAMALANQAfAlANApQAHAVACAYQgmAHggANQhHAbBBgVIBMgaQFiC3knBqQjNBKg6AsQgbATADANQhpEMjrAAQggAAgjgEg");
	this.shape_132.setTransform(252.2,414);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#492513").s().p("AlfYpIAHhoQgQmxhEnCQAhmEhXnEQgEhXgShUQAYhRAjhMQAXgyAcgwIAVANIA9AQQAhAJAfAEQg/CYgWCkQB6OzAoO0gAE70mIgGAGIgeAKQgDAAAngQgAFN20QAxg6Asg6QAjAMAsgEQglA9grA8QgUAfgdAhQgNgpgegkg");
	this.shape_133.setTransform(308.3,519.8);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#C5D644").s().p("AgTAKQAVgQAbgLQgdANgcAWIAJgIg");
	this.shape_134.setTransform(310.6,307);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#663300").s().p("ADvTAQAcl+A+mCQAyj1gKj0QAMiyhFjSQBBgHApgOQAUgFAUgIQAygTAtgnQAkA9AsAtQAhAhAlAXQgeAvgZAyQglBNgZBQQASBVAFBVQBdHGgjGEQBJHBARGxIgIBoIpRAPQANlgBGlUgAr09yIACAAIAogBIANATQAyB8BKBxQgbAKgZAOQhNiNgyiKg");
	this.shape_135.setTransform(198,488.2);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#B6C461").s().p("Ak3CiIgNgUIgpACIgBAAQh+AChRgsQg3gbgpgzQB8AxCdABIAqAAQBAgFBDgLQDDgUA0hjQAngygngxQBwARB0g6QBLgwggglQgFgygegQQg5gmgzgEQA4gIA4AIQBFALA5ARQA2AQAtAuQAfAgAAAoQAVArggAwQEACGirA2Qg9gBhDASIgdAKQiIAthGBfQhSA6gLBjQgBADgUAAQiwgciIA1QhLhxgxh8g");
	this.shape_136.setTransform(159,283.2);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#CADC69").s().p("Ak9EUIgvgIIAeACIABAAQhHgJgqgQQg0gUgKgeIgBgBQhigLgigsIgMgTQgEgKgCgLIAAgDIgBgDIAAgBQgihdEDg1IAAgBIAEgDIgJgMIgHgMIAWg4QAMgHASgGIARgGIAbgKICfgJIAMAEIAOAHIgBgGIgBgFQgPhhDlgmIAIgBIAAAAIALgDIBHgJQAegCAeADICGAjIAeAPIAHADIAWANIB8BzQAyAEA5AmQAfAPAEAyQAgAlhLAwQh0A6hvgSQAmAygmAxQg2BkjDAVQhDALg/AEIgqABQicgBh9gxg");
	this.shape_137.setTransform(123.8,258);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#D2E077").s().p("AipFNIgegCIiygJIgOgCQjSgng4h1QgRgmgDgsIAAAAQgCgpAUghQAshGCRggIANgGQAMgwBRggIATgHQBwgiBkAQIAEgBQAChYDZgeIAJgBQB2gOCMAOIAIABQBSAJBOAoIARAIQAvAXAgAjIAKANQAnA6AIA5IAAACIh8hzIgWgNIgHgDIgegPIiGgjQgegCgeABIhHAJIgLADIAAAAIgIABQjlAnAPBhIABAEIABAGIgOgHIgMgEIifAJIgbAKIgRAGQgSAGgMAIIgWA3IAHAMIAJALIgEADIAAABQkDA1AiBeIAAACIABACIAAADQACAMAEAKIAMASQAiAsBiALIABABQAKAfA0ATQAqAQBHAJg");
	this.shape_138.setTransform(107.3,251.7);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#492513").s().p("Al6YpIAIhoQgRmxhJnCQAjmEhcnEQgGhXgShUQAZhRAlhMQAagyAdgwIAYANIA4AOIAJACQAjAJAiAEQhECYgYCkQCDOzArO0gAFT0lIgHAFIghAKQgDAAArgPgAFm20QA0g6Avg6QAlAMAwgEQgoA9guA8QgWAfgfAhQgOgpgfgkg");
	this.shape_139.setTransform(310.8,519.8);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f("#939E36").s().p("AFPGoQgigFgjgIIgIgCIg5gOIgXgNQgmgXghghQgsgsgkg+QgsAngxAUQgUAHgVAFQgoAOhBAIQgnAEgwABQjLgjiDh9QiuBgjXguQiRgdg3hEQBfArCGghQCsgrCGhQQC1CmDQgnQA9gMA+gcQAvgWAwgfQCoDOC9AHQBKADBMgbIAegMQC4hOAnimQAKgwgDg5QADgSgCgVIA1gYIATgKIAMgGQB9g7AchXQAJgegBggQAPAMAMAOQAgAkAOApQAHAWACAXQF9C3k9BqQj5BTgpArQggAngQAZQhvDkjjAAQghAAgjgEgAOmj9IAHgGQhNAcBGgWg");
	this.shape_140.setTransform(250.5,414);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f("#90A034").s().p("AsVG1QgBgXgGgYQgUhQhLhgQAPACBAggQBIgkAbhrQAGgUAEgWQAJg7gMgtQAVAkAQAlIAQArQAIAWADAWQASBkg8BUQAuAOAygGQApgEAsgRIAggPQCAgGA5hQQBJBKC2hBQBgCwkuAvQgqgLgqALQgWADgTAHQhzAUhUgiIgRACQgwAEglgMQgvA6g1A6QgMgNgOgNgADUA5QA5gvAdg6QAOgfAHghQBrAhBogeQBVgaBShFQBihcgcimQCDBhgGCXQgnCniYA8QhkAahbgaQADAbgTAVQgrgDh0BgQgmAfgbAAQg1AAgFiAg");
	this.shape_141.setTransform(422.9,327.5);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f("#B3BE35").s().p("AkRRZQi9gIipjOQgwAfgvAWQg+Adg9ALQjQAni1inQiGBRisArQiGAihfgrQgYgLgVgPQgbAIgpgqQg8g8g7iMQg3inATiBQAUiTB1hwQAihaB5hDQAVgNAXgMQAZgNAbgKQCIg1CxAcQAUAAABgDQALhjBSg5QBGhgCIgtIAdgKQBDgSA9ABQCMAABsBhIANACIAMACQBQh7BwAZQBfAPA5BZQAZgoAhACQhAhjAVhrQAKjEDwg2IAfgGQBJgMBDATQAXgVAZgPQBhi/DRgaQC+gjCECFQDWjTESAnQEVAUCaDaQDYANAqCvQAbCRiCBLQAcCmhjBcQhSBGhVAZQhnAfhsgiQgHAigOAeQgdA7g5AuQhUDAighzQi2BBhJhKQg4BRiAAFIggAPQgsARgpAFQgyAFgugOQA8hUgShkQgEgWgHgWIgRgrQgQgkgUgkQAMAsgKA6QgEAXgFAUQgcBrhIAkQg/AhgQgDQBMBhAUBQQAFAYABAWQABAhgJAdQgcBYh9A7IgMAGIgTAJIg1AYQACAVgDATQADA4gKAxQgnCni3BOIgeALQhGAZhDAAIgNAAgAAejAIgJAJQAdgYAdgNQgbALgWARg");
	this.shape_142.setTransform(305.6,327.2);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.f("#C5D644").s().p("AgUAKQAWgQAdgLQgfANgfAWIALgIg");
	this.shape_143.setTransform(313.1,307);

	this.shape_144 = new cjs.Shape();
	this.shape_144.graphics.f("#663300").s().p("AD/TAQAfl+BCmCQA2j1gMj0QANiyhKjSQBGgHArgOQAXgFAUgIQA1gTAxgnQAmA9AvAtQAjAhApAXQggAvgbAyQgoBNgbBQQAUBVAFBVQBjHGgmGEQBPHBASGxIgIBoIp6APQAOlgBKlUgAso9yIABAAIArgBIAPATQA1B8BPBxQgcAKgbAOQhSiNg2iKg");
	this.shape_144.setTransform(192.7,488.2);

	this.shape_145 = new cjs.Shape();
	this.shape_145.graphics.f("#B6C461").s().p("AlNCiIgOgUIgrACIgCAAQiHAChWgsQg6gbgsgzQCFAxCnABIAtAAQBEgFBHgLQDRgUA4hjQAqgygqgxQB4ARB8g6QBPgwgiglQgFgygggQQg9gmg2gEQA8gIA8AIQBJALA+ARQA4AQAxAuQAhAgAAAoQAXArgjAwQESCGi2A2QhCgBhHASIggAKQiRAthKBfQhZA6gLBjQgBADgWAAQi8gciSA1QhPhxg1h8g");
	this.shape_145.setTransform(151,283.2);

	this.shape_146 = new cjs.Shape();
	this.shape_146.graphics.f("#CADC69").s().p("AlUEQIgygIIAgACQhIgIgsgPQg8gUgLghIAAAAQiVgQgMhQIgCgIIDjiNIARgEIAAAAIAAgFIgJgLIgGgKIAFgpQAPgSAogNIASgGQAXgIAWgGIB2gKIArALIAOAFIABgCQgXhbDLgqIAwgJIACAAIAEgBIAEgBIAGgBIAKgCIADAAIADgBIEbAiIATAJIAHADIAXANICGB0QA2AEA+AmQAgAPAFAyQAiAmhQAvQh8A6h3gSQApAygpAxQg6BkjQAVQhIALhDAEIgtABQingBiFgxg");
	this.shape_146.setTransform(113.5,258.4);

	this.shape_147 = new cjs.Shape();
	this.shape_147.graphics.f("#D2E077").s().p("AjUFLIi7gJIgPgBQjhgmg9h1QgVgmgCguIAAAAQgDgrAYgiQAxhECcggIAJgIQAQgvBZggIATgGQB3ggBoAPIADgDQAFhXDogdIAKgBQB8gOCSAOIAJABQBWAIBSAnIATAIQAzAXAiAiIAMANQAsA7AIA8IAAABIiGh0IgXgNIgHgDIgTgJIkbgiIgDABIgDAAIgKACIgGABIgEABIgEABIgCAAIgxAJQjKAqAXBbIgBACIgOgFIgrgLIh2AKQgWAGgXAIIgSAGQgoAOgPARIgFApIAGAKIAJAKIAAAFIAAAAIgRAEIjjCOIACAIQAMBQCVAQIAAAAQALAhA8AUQAsAPBIAIg");
	this.shape_147.setTransform(95.7,251.7);

	this.shape_148 = new cjs.Shape();
	this.shape_148.graphics.f("#492513").s().p("AmTYpIAIhoQgSmxhPnCQAmmEhjnEQgFhXgUhUQAbhRAohMQAbgyAggwIAYANIA9AOIAIACQAnAJAjAEQhJCYgZCkQCNOzAtO0gAFq0lIgHAFIgjAKQgDAAAtgPgAF+20QA5g6Ayg6QAoAMAygEQgqA9gxA8QgYAfggAhQgQgpgigkg");
	this.shape_148.setTransform(313.2,519.8);

	this.shape_149 = new cjs.Shape();
	this.shape_149.graphics.f("#939E36").s().p("AFmGoQgkgFgmgIIgJgCIg8gOIgZgNQgogXgjghQgvgsgng+QgvAng1AUQgVAHgWAFQgrAOhGAIQgqAEgzABQjZgjiMh9Qi5BgjmguQicgdg6hEQBlArCPghQC5grCPhQQDBCmDfgnQBAgMBEgcQAxgWA0gfQCzDODKAHQBPADBRgbIAhgMQC9hLAuifQAJgnAAgsQAHgggEgkIA8geIAGgDQCbg+AgheQAKgegBggQAPAMANAOQAiAkAPApQAIAWACAXQGXC3lSBqQkmBbgYArQglA6giAmQh1C8jbAAQgiAAglgEgAPnj9IAHgGQhSAcBLgWg");
	this.shape_149.setTransform(248.8,414);

	this.shape_150 = new cjs.Shape();
	this.shape_150.graphics.f("#90A034").s().p("AtMG1QgBgXgGgYQgVhQhRhgQARACBDggQBNgkAehrQAGgUAEgWQAKg7gMgtQAWAkARAlIARArQAIAWAEAWQATBkhABUQAxAOA1gGQAtgEAvgRIAhgPQCKgGA8hQQBOBKDDhBQBmCwlCAvQgtgLgtALQgXADgWAHQh6AUhagiIgSACQgzAEgogMQgyA6g5A6QgMgNgQgNgADiA5QA9gvAfg6QAPgfAHghQB0AhBugeQBbgaBXhFQBqhcgeimQCMBhgHCXQgqCniiA8QhqAahigaQADAbgVAVQgtgDh8BgQgpAfgcAAQg6AAgFiAg");
	this.shape_150.setTransform(433,327.5);

	this.shape_151 = new cjs.Shape();
	this.shape_151.graphics.f("#B3BE35").s().p("AkkRZQjKgIi0jOQg0AfgyAWQhDAdhAALQjfAnjBinQiPBRi5ArQiPAihmgrQgZgLgWgPQgdAIgtgqQg/g8g/iMQg8inAViBQAWiTB9hwQAjhaCChDQAXgNAYgMQAbgNAcgKQCSg1C9AcQAWAAABgDQALhjBZg5QBKhgCRgtIAggKQBHgSBCABQCVAABzBhIAPACIAMACQBVh7B4AZQBmAPA9BZQAagoAkACQhFhjAXhrQAKjEEBg2IAhgGQA/gJA7AMQAkgOAjgFQBojLDngbQDLgjCNCFQDljTEkAnQEpAUClDaQDmANAtCvQAeCRiMBLQAeCmhqBcQhXBGhbAZQhuAfh0giQgHAigPAeQgfA7g9AuQhaDAiqhzQjDBBhOhKQg8BRiKAFIghAPQgvARgtAFQg1AFgxgOQBAhUgThkQgEgWgIgWIgRgrQgRgkgWgkQAMAsgKA6QgEAXgGAUQgeBrhNAkQhDAhgRgDQBRBhAVBQQAGAYABAWQABAhgJAdQghBfiaA9IgGADIg8AeQADAlgHAfQAAAtgJAnQgtCfi9BMIggALQhLAZhIAAIgNAAgAAgjAIgKAJQAfgYAggNQgdALgYARg");
	this.shape_151.setTransform(307.7,327.2);

	this.shape_152 = new cjs.Shape();
	this.shape_152.graphics.f("#C5D644").s().p("AgVAKQAXgQAfgLQghANggAWIALgIg");
	this.shape_152.setTransform(315.4,307);

	this.shape_153 = new cjs.Shape();
	this.shape_153.graphics.f("#663300").s().p("AEQTAQAgl+BHmCQA5j1gNj0QAOiyhOjSQBKgHAugOQAYgFAWgIQA5gTAzgnQApA9AyAtQAlAhArAXQgiAvgcAyQgrBNgdBQQAWBVAFBVQBqHGgpGEQBUHBATGxIgIBoIqjAPQAPlgBPlUgAtc9yIABAAIAvgBIAPATQA4B8BVBxQgfAKgcAOQhYiNg5iKg");
	this.shape_153.setTransform(187.3,488.2);

	this.shape_154 = new cjs.Shape();
	this.shape_154.graphics.f("#B6C461").s().p("AljCiIgPgUIguACIgCAAQiPAChbgsQg/gbgvgzQCOAxCxABIAxAAQBIgFBMgLQDegUA8hjQAsgygsgxQB/ARCEg6QBVgwgkglQgFgygjgQQhBgmg5gEQBAgIA/AIQBOALBCARQA8AQAzAuQAkAgAAAoQAYArgkAwQEjCGjCA2QhGgBhMASIgiAKQiaAthPBfQheA6gMBjQgCADgXAAQjIgcibA1QhUhxg5h8g");
	this.shape_154.setTransform(143,283.2);

	this.shape_155 = new cjs.Shape();
	this.shape_155.graphics.f("#CADC69").s().p("AkZCAIACAEIAAABIgCgFgAgXgYIgKgMQAGAJAKAJIgCABIgEgHgAEZiAIgBgEIACAFIgBgBg");
	this.shape_155.setTransform(55.7,254.2);

	this.shape_156 = new cjs.Shape();
	this.shape_156.graphics.f("#D2E077").s().p("AkDE3Ig1gIIjEgIIgQgCQjwglhDhzQgWgngDgvIAAgBQgDgtAcgiQA1hECmgfQADgGAFgFQATguBfgeIAVgGQB8gfBuAPIACgEQAHhWD3gdIALgBQCCgNCaANIAIABQBaAHBXAmIATAIQA4AWAlAhIANANQAxA+AKA9IAAABQA5AEBBAmQAjAPAFAyQAkAlhVAwQiEA6h/gSQAsAygsAxQg9BkjeAVQhMALhIAEIgxABQiwgBiOgxgAqJCCIAAgBIgCgEIACAFgAmJgbIAEAGIACAAQgKgJgGgJIAKAMgAhYiDIABABIgCgFIABAEg");
	this.shape_156.setTransform(92.7,254.5);

	this.shape_157 = new cjs.Shape();
	this.shape_157.graphics.f("#492513").s().p("AmtYpIAJhoQgTmxhVnCQApmEhqnEQgFhXgWhUQAdhRArhMQAcgyAigwIAbANIBAAOIAJACQAoAJAnAEQhNCYgcCkQCWOzAwO0gAGB0lIgHAFIgmAKQgDAAAwgPgAGX20QA8g6A1g6QArAMA1gEQgsA9g1A8QgZAfgjAhQgQgpgkgkg");
	this.shape_157.setTransform(315.6,519.8);

	this.shape_158 = new cjs.Shape();
	this.shape_158.graphics.f("#939E36").s().p("AF9GoQgngFgogIIgJgCIhBgOIgagNQgrgXglghQgygsgpg+QgyAng5AUQgWAHgYAFQguAOhKAIQgsAEg3ABQjngjiVh9QjFBgj1guQilgdg/hEQBsArCZghQDEgrCYhQQDOCmDtgnQBFgMBHgcQA1gWA3gfQC/DODXAHQBUADBWgbIAjgMQDEhJAziWQAJgeACghQAKgtgFg0QAbgRAUgIIACgBQC3hAAlhlQALgegCggQARAMAOAOQAkAkAQApQAIAWADAXQGxC3loBqQlTBjgGArQgrBNg1AyQh6CVjPAAQglAAgogEgAQnj9IAHgGQhXAcBQgWg");
	this.shape_158.setTransform(247.1,414);

	this.shape_159 = new cjs.Shape();
	this.shape_159.graphics.f("#90A034").s().p("AuCG1QgBgXgGgYQgXhQhWhgQASACBIggQBSgkAfhrQAGgUAFgWQALg7gOgtQAYAkASAlIASArQAJAWAEAWQAUBkhEBUQA0AOA5gGQAvgEAygRIAkgPQCSgGBAhQQBTBKDQhBQBtCwlYAvQgvgLgwALQgZADgWAHQiDAUhfgiIgUACQg2AEgqgMQg2A6g8A6QgOgNgQgNgADxA5QBBgvAhg6QAQgfAIghQB6AhB2geQBhgaBdhFQBwhcggimQCVBhgHCXQgtCnitA8QhxAahogaQAEAbgWAVQgxgDiEBgQgsAfgeAAQg9AAgFiAg");
	this.shape_159.setTransform(443.1,327.5);

	this.shape_160 = new cjs.Shape();
	this.shape_160.graphics.f("#B3BE35").s().p("Ak3RZQjXgIjAjOQg3Afg1AWQhHAdhFALQjtAnjOinQiYBRjEArQiZAihsgrQgbgLgYgPQgeAIgvgqQhEg8hDiMQg/inAViBQAYiTCFhwQAmhaCKhDQAYgNAagMQAcgNAfgKQCbg1DJAcQAXAAABgDQAMhjBeg5QBPhgCbgtIAhgKQBNgSBFABQCfAAB7BhIAPACIANACQBbh7CAAZQBsAPBBBZQAcgoAmACQhJhjAYhrQALjEERg2IAjgGQA2gHAyAGQAxgGAvAEQBtjYD9gbQDZgjCWCFQDzjTE4AnQE7AUCwDaQD1ANAwCvQAfCRiUBLQAfCmhwBcQhdBGhhAZQh1Afh7giQgIAigQAeQghA7hBAuQhgDAi1hzQjPBBhThKQhABRiSAFIgkAPQgyARgvAFQg5AFg0gOQBEhUgVhkQgEgWgIgWIgTgrQgSgkgXgkQANAsgLA6QgEAXgGAUQggBrhSAkQhIAhgSgDQBXBhAWBQQAGAYABAWQACAhgLAdQglBmi3A/IgCABQgUAJgbARQAFA0gKAtQgCAhgJAdQgzCXjDBKIgjALQhPAZhNAAIgOAAgAAijAIgLAJQAigYAhgNQgfALgZARg");
	this.shape_160.setTransform(309.8,327.2);

	this.shape_161 = new cjs.Shape();
	this.shape_161.graphics.f("#663300").s().p("AC8d0QAQlgBVlUQAhl+BLmCQA9j1gNj0QAOiyhSjSQBOgHAxgOQAZgFAYgIQAZAwARAvQAbAvAWAvIAXj3QArA9A1AtIATCZQgtBNgfBQQAXBVAGBVQBwHGgrGEQBZHBAUGxIgJBoIgBAPgAuQ9yQAZABAZgCQAAAMAQAFIAAACQA8B8BaBxQghAKgeAOQhdiNg8iKg");
	this.shape_161.setTransform(181.9,488.2);

	this.shape_162 = new cjs.Shape();
	this.shape_162.graphics.f("#B6C461").s().p("ACWGBIAXgDIADAAQgCADAAADIgYgDgAkSCuQhLAGgbgKQgQgEAAgNQgaACgZAAQiYABhhgrQhCgbgygzQCWAxC9ABIAzgBQBNgEBQgLQDsgVA/hjQAvgxgvgyQCHASCMg6QBagwgmgmQgGgygkgPQhFgmg9gEQBEgIBDAIQBTALBFAQQBAARA3AuQAlAfAAApQAaArgnAvQE1CGjOA2QhJAAhRASIgkAJQiRALjcgBQg0AXhRANQhIAhhEgCQg8ARg5AAQgcAAgbgEg");
	this.shape_162.setTransform(135,282.1);

	this.shape_163 = new cjs.Shape();
	this.shape_163.graphics.f("#CADC69").s().p("Al+EUIgUgGQi+gTgVg5QirgQgMhUQgthgFDg2QhIhCCAgiQCeg2BoAtQglhrEsgoQC+gmC4BNQBvAzBHBQQA9AEBFAmQAkAPAGAyQAmAlhaAwQiMA6iHgSQAvAygvAxQhABkjsAVQhQALhNAEIgyABQi9gBiWgxg");
	this.shape_163.setTransform(92.4,258);

	this.shape_164 = new cjs.Shape();
	this.shape_164.graphics.f("#D2E077").s().p("AnMFCQj/glhJhxQgagogCgyQgDgvAfgjQA6hDCxgeQANg2B1giQCOglB9ARQAAhaERgeQCRgOCrAOQBpAIBlAsQBHAZArAqQA3A/AKBAQhHhQhvgzQi4hNi+AmQksAoAlBrQhogtieA2QiAAiBIBBQlDA2AtBhQAMBUCrAQQAVA5C+ATg");
	this.shape_164.setTransform(72.5,251.7);

	this.shape_165 = new cjs.Shape();
	this.shape_165.graphics.f("#939E36").s().p("AGUGoQgpgFgqgIIhPgQIgcgNQgtgXgoghQg1gsgrg+Qg1Ang8AUQgYAHgZAFQgxAOhOAIQgwAEg5ABQj1gjieh9QjRBgkEguQiwgdhChEQBzArChghQDRgrChhQQDaCmD8gnQBIgMBMgcQA4gWA7gfQDKDODkAHQBZADBcgbIAkgMQDLhHA5iOQAIgUAFgVQAOg6gHhEIgBgLIAhgJQDUhCAphsQALgegBggQARAMAPAOQAmAkARApQAJAWADAXQgxAHgpANQhcAcBUgWIBigaQHLC3l+BqQl/BrALArQgwBhhHA+Qh+BtjEAAQgpAAgsgEg");
	this.shape_165.setTransform(245.3,414);

	this.shape_166 = new cjs.Shape();
	this.shape_166.graphics.f("#492513").s().p("AnHYpIAJhoQgUmxhZnCQArmEhwnEQgGhXgXhUQAehRAuhMQAegyAkgwIAcANIBOAQQArAJAoAEQhSCYgcCkQCeOzA0O0gAGZ0lIgIAFIgoAKQgEAAA0gPgAGv20QBBg6A4g6QAtAMA5gEQgwA9g3A8QgbAfglAhQgRgpgngkg");
	this.shape_166.setTransform(318,519.8);

	this.shape_167 = new cjs.Shape();
	this.shape_167.graphics.f("#90A034").s().p("AwzD6QATADBMghQBXgkAhhrQAHgUAEgXQAMg6gOgsIgEgMIAIANQAjA4AYA6QAJAWAFAWQAVBkhIBUQA3AOA9gFQAygFA1gRIAmgPQCbgFBEhRQBYBKDchBQBzCwlsAvQgygLgzALQgaAEgYAGQiKAUhmgiIgVACQg5AEgtgMQgvgMgjgcQhNAUgBBAQgYhQhbhhgAEABdQBEguAjg7QARgeAJgiQCCAiB8gfQBngZBjhGQB3hcgiimQCeBigICWQgvCni3A8Qh4AahvgaQAEAcgXAUQgzgDiMBgQgvAfggAAQhBAAgFiAg");
	this.shape_167.setTransform(453.2,323.8);

	this.shape_168 = new cjs.Shape();
	this.shape_168.graphics.f("#B3BE35").s().p("AllQEQjkgIjMjOQg6Afg4AWQhMAdhJALQj7AnjainQiiBRjQArQiiAihygrQgdgLgZgPQg+glgshAQiLjGAdidQAVhuBSheQARgVAVgUQATgSAWgSQCZh9EigcQEhgdCxCAQAbioBehIQBghKB3ghQBfgbBtAAQBrAABVAhQBHAbA5AyQAcgaAbgUQB3hYBsAeQBJAUBDBIQAXgpAngcIALgJQAjgWAvgOIAbgHQATgEAUgDQCigYB7A+QAWAMATAPQgQg/hNgeIgZgQQhPgwhRgWQgrgNgsgFQhKgJhLALQAeiEB3g8QA1gaBFgMQBwglCdAnIAJgTQAOggATgcQBsioDqgTQCEgDBuAjQAvAPAsAXQAfAQAdAUIAggYQAegXAfgUQFKjPGhCmQEEANAzCvQAhCRidBLQAhCmh3BcQhiBGhnAZQh9AfiCgiQgIAigRAeQgjA8hFAuQhmC/jAhzQjcBBhYhKQhEBRibAFIgmAPQg1ARgyAFQg8AFg3gOQBIhUgWhjQgEgWgJgWQgYg7gjg4IgJgNIAEAMQAPAsgMA7QgFAXgGAUQgiBqhXAkQhMAhgTgDQBcBhAYBQQAGAYABAWQACAhgLAdQgqBtjUBBIghAKIACAKQAGBEgOA6QgFAVgIAUQg5CQjJBHIglALQhUAZhRAAIgPAAgA6LhqQAhABAfAEIASADIgBAFQgpgIgogFg");
	this.shape_168.setTransform(314.6,335.7);

	this.shape_169 = new cjs.Shape();
	this.shape_169.graphics.f("#C5D644").s().p("EghGAPnQhIg9hHiLQhDioAXiAQAZiTCNhwQAohbCShCQAagPAbgLQAegOAhgJQCkg0DVAbIAZADQAAgDABgDQANhiBkg6QBUhfCjguIAkgJQBRgSBKAAQCoAACDBiIAQABIAOACQBgh7CHAaQBzAPBFBYIAGAAQAXgnApACQhOhkAahqQALjEEjg2IAlgGQAsgGAqABQA9AAA6APQBzjkEUgcQDlgkCfCGQEDjUFKAoQFPATC6DbQmiinlJDQQgfATgfAXIgfAZQgdgUgggRQgrgWgwgPQhugjiEADQjqAShsCpQgTAcgOAgIgIATQiegohwAmQhFAMg0AaQh4A7gfCFQBNgLBKAJQAsAFAqAMQBSAXBOAwIAZAQQBNAeAQA+QgSgPgXgLQh7g/iiAYQgUADgSAEIgcAIQgvANgjAXIgLAIQgnAdgXApQhEhJhHgUQhsgdh3BYQgbAUgcAaQg5gzhHgbQhWghhqAAQhuAAhfAbQh2AhhhBJQheBJgaCpQixiCkiAdQkhAdiZB9QgWASgTATQgVATgSAVQhSBfgUBuQgdCcCKDGQAtBAA9AlIgKACQgeAAgqgjgA2ABHIAAgGIgRgCQgfgEghgBQAnAFAqAIg");
	this.shape_169.setTransform(296,319.3);

	this.shape_170 = new cjs.Shape();
	this.shape_170.graphics.f("#A1BF37").s().p("ABfGhQk0B6jXjYIgXAPQiwBtjChuQgwgbgxgpQAthHA1gwIAbgXQCpiCD4BWQCNjfD6gKQHHosFbGGQAxA3AvBLQAaDFheCkQgNAWgPAVQgWAfgaAeQi1C3jLAPIgiABQh8AAiEg9g");
	this.shape_170.setTransform(244.7,230.7);

	this.shape_171 = new cjs.Shape();
	this.shape_171.graphics.f("#7AA234").s().p("AgbIJQjFADifhwQghAggyAJQhnAhgxhCQghgUgSgcQhvAahegWQgVgEgUgIQhrglhShoQgmgngUhAIgCgIQgJgrgEgnQAxApAwAbQDCBuCwhtIAXgPQDXDYE1h6QCWBGCLgKQDLgPC1i3QAageAWgeQAPgVAMgWQBfikgajGQgGgmgMglQEIhFCeCmQAuAqAcAxQA1BcgIBzQgFA/gYBGQiPEuldhQQgcBBgqApQgNANgPALQheBDiYggQilBqiXAAIgXAAg");
	this.shape_171.setTransform(270.6,254.6);

	this.shape_172 = new cjs.Shape();
	this.shape_172.graphics.f("#B1D93D").s().p("AuLErIADgMQAqigC8gmQBagYA+AYQAVisCUguQATgGAUgDQAngLAnALQA6hvBVhHQBwhfCjgXQBVgNBiAHQApADAmAGQERAqBoCaIAIANQAuBEAYBLQAMAlAGAmQgvhLgxg3QlamFnIIqQj6AKiNDgQj4hWipCCIgbAXQg1AwgtBHQgIhTAPhBg");
	this.shape_172.setTransform(244.3,212.9);

	this.shape_173 = new cjs.Shape();
	this.shape_173.graphics.f("#B6C461").s().p("AFOEMIAXgDIADAAQgCADAAAEIgYgEgAhaA5QhLAHgbgKQgQgFAAgMQgaABgZAAQiYAChhgrQhCgbgygyQCWAxC9AAIAzAAQBNgEBQgLQDrgVBAhkQAvgygvgxQBNAKBPgPQAUBBAlAmQBTBoBrAmQh1AFiZgBQg0AWhRAOQhJAghEgCQg8ARg4AAQgcAAgbgEg");
	this.shape_173.setTransform(116.6,293.7);

	this.shape_174 = new cjs.Shape();
	this.shape_174.graphics.f("#CADC69").s().p("AkiEUIgUgGQi/gTgVg5QirgQgLhUQguhgFEg2QhIhCB/giQCfg2BoAtQglhrErgoQC+gmC5BNQBoAwBFBKQgOBBAIBTQAEAmAJArIACAIQhPAOhMgKQAvAygvAxQhBBkjrAVQhRALhMAEIg0ABQi7gBiWgxg");
	this.shape_174.setTransform(83.2,258);

	this.shape_175 = new cjs.Shape();
	this.shape_175.graphics.f("#D2E077").s().p("AnKFCQj/glhJhxQgZgogDgyQgDgvAfgjQA7hDCwgeQANg2B1giQCOglB9ARQAAhaERgeQCRgOCrAOQBpAIBlAsQBHAZArAqQAuA1AOA1IgDAMQhFhKhpgwQi4hNi+AmQksAoAkBrQhngtieA2QiAAiBIBBQlDA2AtBhQAMBUCrAQQAVA5C+ATg");
	this.shape_175.setTransform(72.3,251.7);

	this.shape_176 = new cjs.Shape();
	this.shape_176.graphics.f("#B3BE35").s().p("AllQEQjkgIjMjOQg6Afg4AWQhMAdhJALQj7AnjainQiiBRjQArQiiAihygrQgdgLgZgPQg+glgshAQiLjGAdidQAVhuBSheQARgVAVgUQATgSAWgSQCZh9EigcQEhgdCxCAQAbioBehIQBghKB3ghQBfgbBtAAQBrAABVAhQBHAbA5AyQAcgaAbgUQB3hYBsAeQBJAUBDBIQAXgpAngcIALgJQAjgWAvgOIAbgHQATgEAUgDQCigYB7A+QAWAMATAPQgQg/hNgeIgZgQQhPgwhRgWQgdgJgdgFQAqgpAchBQFdBRCPkvQAYhGAFhAQBFgbBWgHQCEgDBuAjQAvAPAsAXQAfAQAdAUIAggYQAegXAfgUQFKjPGhCmQEEANAzCvQAhCRidBLQAhCmh3BcQhiBGhnAZQh9AfiCgiQgIAigRAeQgjA8hFAuQhmC/jAhzQjcBBhYhKQhEBRibAFIgmAPQg1ARgyAFQg8AFg3gOQBIhUgWhjQgEgWgJgWQgYg7gjg4IgJgNIAEAMQAPAsgMA7QgFAXgGAUQgiBqhXAkQhMAhgTgDQBcBhAYBQQAGAYABAWQACAhgLAdQgqBtjUBBIghAKIACAKQAGBEgOA6QgFAVgIAUQg5CQjJBHIglALQhUAZhRAAIgPAAgA6LhqQAhABAfAEIASADIgBAFQgpgIgogFg");
	this.shape_176.setTransform(314.6,335.7);

	this.shape_177 = new cjs.Shape();
	this.shape_177.graphics.f("#C5D644").s().p("EghGAPnQhIg9hHiLQhDioAXiAQAZiTCNhwQAohbCShCQAagPAbgLQAegOAhgJQCkg0DVAbIAZADQAAgDABgDQANhiBkg6QBFhPB8gtQBeAWBvgaQASAcAhAUQAxBCBnghQAygJAhggQCfBwDFgDQCiAJCxhzQCYAgBehDQAPgLAOgNQAdAFAcAIQBSAXBOAwIAZAQQBNAeAQA+QgSgPgXgLQh7g/iiAYQgUADgSAEIgcAIQgvANgjAXIgLAIQgnAdgXApQhEhJhHgUQhsgdh3BYQgbAUgcAaQg5gzhHgbQhWghhqAAQhuAAhfAbQh2AhhhBJQheBJgaCpQixiCkiAdQkhAdiZB9QgWASgTATQgVATgSAVQhSBfgUBuQgdCcCKDGQAtBAA9AlIgKACQgeAAgqgjgA2ABHIAAgGIgRgCQgfgEghgBQAnAFAqAIgAWDrNQgrgWgwgPQhugjiEADQhWAHhFAbQAJhzg2hcQC8gKCIBzQEDjUFKAoQFPATC6DbQmiinlJDQQgfATgfAXIgfAZQgdgUgggRg");
	this.shape_177.setTransform(296,319.3);

	this.shape_178 = new cjs.Shape();
	this.shape_178.graphics.f("#B6C461").s().p("AgNMNIAWgDIADAAQgCADAAAEIgXgEgAm2I6QhLAHgbgKQgQgFAAgMQgaABgZAAQiYAChhgsQhCgbgygyQCWAxC9AAIAzAAQBNgEBQgLQDsgVBAhkQAvgygvgxQBNAKBOgPQAUBBAlAmQBTBoBrAmQh1AFiZgBQgzAXhRAOQhJAghEgCQg8ARg5AAQgcAAgbgEgABbBRQgRAFgMAAQggAAAAgjIgQACQhVAGg1hCQgigpgahNQBAA8BMALQAZADAagBQARgCASgDQAbgFAcgLQBjgZAphoQAKgYAGgcQAWhLgWhKQBEAaBIhYQAvhFgUg5QgEhKgSgXQgjg7gggGQAjgMARgOQARgOAnAdQAmAdApBUQApBSAAA7QBRAbBBAaQDkBbAiBNQA1B5mtBWQg7ALhFAMQhDALhMAKQgbAlgqATQgkAwgkgEQgeAZgdAAQgPAAgOgGg");
	this.shape_178.setTransform(151.4,242.4);

	this.shape_179 = new cjs.Shape();
	this.shape_179.graphics.f("#CADC69").s().p("AnoLAIgUgGQi/gTgVg5QirgQgLhUQguhhFEg2QhIhCB/giQCfg2BoAtQglhrEsgoQBTgQBTAFQAQAKASAHIB8APIAKADIgCgCQhUgYgUhCQgDgMgCgMQhYgXgHh9QgViRClhRQgmhjBDg0QBRhQA2BEQgTigCbg8QBig5BeBzQA5BMAkB4QAgAGAjA6QASAXAEBKQAUA6gvBEQhIBYhEgaQAXBLgXBJQgGAdgKAYQgpBnhjAaQgcAKgbAGQgSADgRABQgaACgZgDQhNgLg/g9QAaBOAhApQA2BDBVgGQgEAtAFA1QAEAnAJArIACAIQhPAOhMgKQAvAygvAxQhBBkjrAVQhQALhMAEIg0ABQi8gBiWgxg");
	this.shape_179.setTransform(103,215.2);

	this.shape_180 = new cjs.Shape();
	this.shape_180.graphics.f("#D2E077").s().p("ApjMAQj/glhJhyQgagogCgxQgDgvAfgkQA6hDCxgeQANg2B1giQCOglB9ARQAAhaESgeQBtgLB9AGQhGhggDiwQgEjHCMhGQAGhRA8gzQBKg1A/AYQABiICMgtQBMgTBXATQA3AMA0BEQAkAlAXA9QAbBfAFBgQglh4g4hMQhfhzhhA5QicA8AUCgQg3hEhQBQQhDA0AmBjQimBRAWCRQAHB9BYAXQABAMADALQAUBDBVAYIACACIgKgDIh8gPQgSgIgQgJQhTgGhUARQksAoAlBrQhogtieA2QiAAiBIBCQlDA2AtBhQAMBUCrAQQAVA5C+ATg");
	this.shape_180.setTransform(87.6,207.1);

	this.shape_181 = new cjs.Shape();
	this.shape_181.graphics.f("#A1BF37").s().p("ABfGhQk0B6jXjYIgXAPQiwBtjChuQgwgbgxgpQAXgkAYgeQAMAAARgFQAqAUAugmQAkAEAkgxQArgUAagkQBMgLBEgLQAtAJAwARQAQgaASgXQGshVg1h5QG8oOFUF+QAxA3AvBLQAaDFheCkQgNAWgPAVQgWAfgaAeQi1C3jLAPIgiABQh8AAiEg9g");
	this.shape_181.setTransform(244.7,230.7);

	this.shape_182 = new cjs.Shape();
	this.shape_182.graphics.f("#B1D93D").s().p("AuTFdIAQgCQAAAjAgAAQgYAegXAjQgFg1AEgtgAnRDrQBEgLA7gMQgRAXgRAaQgwgRgtgJgAjfihQA2hfBMhAQBwhfCjgXQBVgNBiAHQApADAmAGQERAqBoCaIAIANQAuBEAYBLQAMAlAGAmQgvhLgxg3QlUl+m8IOQgihMjihbg");
	this.shape_182.setTransform(244.3,212.9);

	this.shape_183 = new cjs.Shape();
	this.shape_183.graphics.f("#CADC69").s().p("Ax1OrIgUgHQi/gTgVg5QirgPgLhUQguhhFEg2QhIhDB/ghQCfg2BoAsQglhqEsgoQBUgRBTAGQAQAJASAHIB8APIAKAEIgCgDQhUgXgUhDQgDgLgCgNQhYgXgHh+QgViPClhSQgmhjBDgzQBRhQA2BEQgTigCbg9QAxgcAvAOQgBgjAugnIASgNQCKhSCDAYQgrhFArhGQBCiMDqgeQE6g4DkBpIASAJQC9AaAUBRQCqAVANB2QAqCHk/BMQBJBciBAxQiaBLhphAQAJAngNAhQgkBdjeApQgiAKgiAEQiPATiNhNIgRgKQhKgxg4hDQgagfgXgkIgDAAQgMgCgMgDQASAqAPAxQAHACAIAEQAPArAaArQANATARAQIADAjQAUA5gvBEQhIBYhEgaQAXBKgXBLQgGAcgKAYQgpBohiAZQgcALgbAFQgSAEgRABQgaACgZgEQhNgKg/g9QAaBNAhApQA2BDBVgGQgEAuAFA1QAEAnAJArIACAHQhPAPhMgKQAvAxgvAyQhBBkjrAVQhRALhMAEIg0AAQi8AAiWgxg");
	this.shape_183.setTransform(168.3,191.7);

	this.shape_184 = new cjs.Shape();
	this.shape_184.graphics.f("#B6C461").s().p("AgNMAIAWgDIADAAQgCADAAADIgXgDgAm2ItQhLAGgbgKQgQgEAAgNQgaACgZAAQiYABhhgrQhCgbgygzQCWAxC9ABIAzgBQBNgEBQgLQDsgVBAhkQAvgxgvgyQBNAKBOgOQAUBBAlAmQBTBoBrAmQh1AFiZgBQgzAXhRANQhJAhhEgCQg8ARg5AAQgcAAgbgEgABbBDQgRAGgMAAQggAAAAgjIgQACQhVAGg1hCQgigpgahOQBAA9BMALQAZADAagCQARgBASgDQAbgGAcgKQBjgaAphnQAKgYAGgdQAWhKgWhLQBEAaBIhYQAvhEgUg6IgDgjQAjAiAwAXQARAMARAJIAXALQACAPAAANQBRAbBBAaQDkBbAiBNQA1B5mtBVQg7AMhFALQhDALhMALQgbAkgqATQgkAxgkgEQgeAZgdAAQgPAAgOgHgAFLr+IALgEIADAJQgHgEgHgBg");
	this.shape_184.setTransform(151.4,243.8);

	this.shape_185 = new cjs.Shape();
	this.shape_185.graphics.f("#D2E077").s().p("A2JOPQj/glhJhyQgZgogDgyQgDguAfgkQA7hDCwgeQANg2B1gjQCOgkB9ARQAAhaESgeQBugLB9AGQhGhggDixQgEjHCMhGQAGhQA8gzQBKg1A/AXQABiICMgsQBMgUBXAUQAcAGAaAUQgvAnACAjQgwgOgwAdQicA8AUCgQg3hEhQBQQhDA0AmBiQimBSAWCQQAHB9BYAXQABANAEALQATBDBVAYIACACIgKgDIh8gQQgSgHgQgJQhTgGhUARQktAoAlBrQhogtieA2QiAAiBIBCQlDA2AtBhQAMBUCrAQQAVA5C+ASgAIvACIgWgCQhLgGhJgjIgXgLQgRgKgRgLQgwgXgjgiQgRgQgOgTQgZgrgQgrIgDgKQgNgpgEgpQAWAkAbAfQA4BEBJAxIASAJQCMBNCQgTQAigEAigJQDdgqAlhdQANghgKgmQBpA/CbhLQCBgwhJhdQE+hMgpiGQgOh3ipgVQgUhRi+gaID+AQQBeASBEAiQC5BZAHDDQAHCgjHBGQggAMglAJQgMBMhzAvIgLAEQiIAth1gVQgBBHhUAsQhDAjh3ARQhJAJhOAAQhFAAhIgHgACBlcQANADAMACQAHArACArQgPgxgTgqg");
	this.shape_185.setTransform(168.2,192.8);

	this.shape_186 = new cjs.Shape();
	this.shape_186.graphics.f("#939E36").s().p("AGDGoQgpgFgqgIIhPgQIgcgNQgtgXgoghQg1gsgrg+Qg1Ang8AUQgYAHgZAFQgxAOhOAIQgwAEg5ABQj1gjieh9QjRBgkEguQiJgXhHguQAXgCAZgGQBXAMBrgWQBogWBbgeQCsB0DFhTQBhAhBogDQC2CsDOhOQBBgaAwglQCBBOCKAEQBZADBcgbIAkgMQDLhHA5iOQAIgUAFgVQAOg6gHhEIgBgLIAhgJQDUhCAphsQALgegBggQARAMAPAOQAmAkARApQAJAWADAXQgxAHgpANQhcAcBUgWIBigaQHLC3l+BqQl/BrALArQgwBhhHA+Qh+BtjEAAQgpAAgsgEg");
	this.shape_186.setTransform(247,414);

	this.shape_187 = new cjs.Shape();
	this.shape_187.graphics.f("#90A034").s().p("AwzD6QATADBMghQA0gWAhgwQA5gcBDgPQAMBbhCBNQA3AOA9gFQAygFA1gRIAmgPQCbgFBEhRQBYBKDchBQBzCwlsAvQgygLgzALQgaAEgYAGQiKAUhmgiIgVACQg5AEgtgMQgvgMgjgcQhNAUgBBAQgYhQhbhhgAEABdQBEguAjg7QARgeAJgiQCCAiB8gfQBngZBjhGQB3hcgiimQCeBigICWQgvCni3A8Qh4AahvgaQAEAcgXAUQgzgDiMBgQgvAfggAAQhBAAgFiAg");
	this.shape_187.setTransform(453.2,323.8);

	this.shape_188 = new cjs.Shape();
	this.shape_188.graphics.f("#A1BF37").s().p("AmsFLIgXAPQiwBtjChuQgwgbgxgoQAXgkAYgeQAMAAARgFQAqATAugmQAkAEAkgwQArgUAaglQBMgKBEgLQAtAIAwARQAQgZASgXQGshVg1h5QG8oPFUF+QAxA4AvBKQAVCgg5CIQgdgFgfgBIggAAQjbAXhNDzQh6gnhWAlQhTATgzA0QgagKgagMQhuAshkAAQivAAiKiKg");
	this.shape_188.setTransform(244.7,229.8);

	this.shape_189 = new cjs.Shape();
	this.shape_189.graphics.f("#B1D93D").s().p("AuTFBIAQgBQAAAjAggBQgYAegXAkQgFg1AEgugAnRDQQBEgLA7gMQgRAXgRAaQgwgRgtgJgAjfi8IAWglQCbAPCHgRQB4gSBCgjQBVgsABhHQB0AVCJgtQCLA0BEBkIAIAOQAuBEAYBLQAMAlAGAmQgvhLgxg3QlUl+m8IOQgihMjihbg");
	this.shape_189.setTransform(244.3,215.6);

	this.shape_190 = new cjs.Shape();
	this.shape_190.graphics.f("#7AA234").s().p("Al7GfQgiAggxAJQhoAhgxhCQghgUgRgcQhvAahegWQgVgEgVgIQhqglhThoQgmgngUhAIgCgIQgIgrgEgnQAxApAvAbQDCBuCxhtIAXgPQDXDYE1h6QAZAMAaAJQg6A7gSBlQCrggCaCGQAVAKAQAPQgXAJgWAGQhNgfheASQgtAJgiASQiOgTh4hUgAJth+QA5iJgUifQgHgmgLglQEIhFCeCmQAtAqAcAxQAcAwALA3Qi4ANidCoQhbhSh5gTg");
	this.shape_190.setTransform(270.3,254.3);

	this.shape_191 = new cjs.Shape();
	this.shape_191.graphics.f("#B3BE35").s().p("AxQOQQhnADhighQjEBUith1QhbAehoAWQhrAWhXgLQgYAFgYACQhPAHg/geQgWgKgTgQQgwglgihAQhOiQgJh5QgEguAGgrQAXidB2h9QB2h9DfgcQBRgKBEAKIAogFQBngKBZAKQALgnAQgfQgqgIgngFQAhABAfAEIARACIAAAFQATgnAagaQCHiGC9AAQBbAABGAoQAagKAbgIQBfgbBuAAQBqAABWAhIAHADQAVgUAZgNQAjgTAtgJQBegSBOAgIAZALQAUgCAUABQgJgOgMgMQgPgPgVgKQiciGiqAgQAShlA6g6QAzg0BTgTQBWgmB6AoQBNj0DagWIAgAAQAfABAdAFQB5ATBbBRQCdinC4gOQCRgLCiBUQBkAGA8AvIAbANQAgARAdAUIAfgZQAfgXAfgTQFJjQGiCnQEEANAyCvQAiCRieBLQAiCmh3BcQhjBFhnAaQh8AeiCghQgJAhgRAfQgjA7hEAvQhmC+jAhyQjcBAhYhJQhEBQibAGIgmAOQg1ASgyAEQg9AFg3gNQBDhNgNhaQhCAOg5AcQghAwg1AWQhMAggTgDQBbBhAYBQQAHAYABAXQABAggLAeQgpBsjUBCIghAJIABALQAHBEgOA6QgFAVgIAUQg5CQjKBGIgkAMQhcAbhZgDQiKgEiBhOQgwAlhCAaQhAAYg/AAQiIAAh9h2g");
	this.shape_191.setTransform(312.3,336);

	this.shape_192 = new cjs.Shape();
	this.shape_192.graphics.f("#C5D644").s().p("EgkBAKsQAZiTCNhwQAohaCShDQAagOAbgMQAegNAhgKQCkg1DVAcIAZAEQAAgEABgDQANhjBkg5QBFhOB8gtQBeAVBvgaQASAcAhAVQAxBBBnghQAygJAhggQB4BUCOATQgZAOgVAUIgHgDQhWghhqAAQhuAAhfAbQgbAHgaAKQhGgnhbAAQi9AAiHCGQgaAagTAmIAAgEIgRgDQgfgEghgBQAnAFAqAIQgQAfgLAnQhZgKhnALIgoAEQhFgKhQALQjfAdh2B9Qh2B9gXCcQgGArAEAuQgThbAOhNgAh7AkQAWgHAWgIQAMALAJAPQgUgCgUADIgZgMgAWDoXIgbgOQg8guhkgHQiihUiRALQgLg2gcgxQC8gJCIByQEDjTFKAnQFPAUC6DaQmiimlJDPQgfAUgfAXIgfAYQgdgUgggQg");
	this.shape_192.setTransform(296,301.1);

	this.shape_193 = new cjs.Shape();
	this.shape_193.graphics.f("#B6C461").s().p("ACWMAIAYgDIADAAQgCADAAADIgZgDgAkRItQhMAGgagKQgRgEABgNQgaACgZAAQiYABhhgrQhCgbgygzQCWAxC8ABIA0gBQA/gDBBgIQATAwAbAzIAEAFQgSgBgQgCgAGPjRIADgGQAJgYAHgdQAWhKgWhLQBEAaBHhYQAwhEgVg6IgCgjQAjAiAvAXQARAMASAJIAXALQACAPAAANIBUAdQhwAfhZBYQhIBIgVCpQgzgwhAgbgAHvr+IAMgEIADAJQgHgEgIgBg");
	this.shape_193.setTransform(134.9,243.8);

	this.shape_194 = new cjs.Shape();
	this.shape_194.graphics.f("#D2E077").s().p("A2HOPQj/glhJhyQgagogCgyQgDguAfgkQA6hDCxgeQANg2B1gjQCOgkB9ARQAAhaESgeQBugLB9AGQhGhggDixQgEjHCMhGQAGhQA8gzQBKg1A/AXQABiICMgsQBMgUBXAUQAcAGAaAUQgvAnACAjQgwgOgwAdQicA8AUCgQg3hEhQBQQhDA0AmBiQimBSAWCQQAHB9BYAXQABANADALQAOAvAuAaIgSAKIhFgJQgSgHgQgJQhTgGhUARQktAoAlBrQhogtieA2QiAAiBIBCQlDA2AtBhQAMBUCrAQQAVA5C+ASgAKsAJQgngJgtAAQgXAAgXACIgPgCQhMgGhIgjIgXgLQgRgKgRgLQgwgXgjgiQgRgQgOgTQgagrgPgrIgDgKQgNgpgEgpQAWAkAaAfQA4BEBKAxIASAJQCMBNCQgTQAigEAigJQDdgqAlhdQANghgKgmQBpA/CbhLQCBgwhJhdQE+hMgpiGQgOh3ipgVQgUhRi+gaID+AQQBdASBFAiQClBQAYClQhsBBgxCcIgggJQhlgahLAhQiwAogiC9QgmAAgkgHQgBBHhUAsQhDAjh3ARQhKAJhPAAIgQAAgACDlcQANADAMACQAHArACArQgPgxgTgqg");
	this.shape_194.setTransform(168,192.8);

	this.shape_195 = new cjs.Shape();
	this.shape_195.graphics.f("#CADC69").s().p("Ax1OrIgUgHQi/gTgVg5QirgPgLhUQguhhFEg2QhIhDB/ghQCfg2BoAsQglhqEsgoQBUgRBTAGQAQAJASAHIBGAJQg3AggpArQh2B9gWCdQgRB0A3CMQhCAIg+ADIg0AAQi8AAiWgxgAnTEZQgDgLgCgNQhYgXgHh+QgViPClhSQgmhjBDgzQBRhQA2BEQgTigCbg9QAxgcAvAOQgBgjAugnIASgNQCKhSCDAYQgrhFArhGQBCiMDqgeQE6g4DkBpIASAJQC9AaAUBRQCqAVANB2QAqCHk/BMQBJBciBAxQiaBLhphAQAJAngNAhQgkBdjeApQgiAKgiAEQiPATiNhNIgRgKQhKgxg4hDQgagfgXgkIgDAAQgMgCgMgDQASAqAPAxQAHACAIAEQAPArAaArQANATARAQIADAjQAUA5gvBEQhIBYhEgaQAXBKgXBLQgGAcgKAYIgDAHQhogsiLASQiFAShfAzQgugagOgvg");
	this.shape_195.setTransform(168.3,191.7);

	this.shape_196 = new cjs.Shape();
	this.shape_196.graphics.f("#A1BF37").s().p("ABuDpQAPADA7ghQAbgPAVgbQAngzAOhdQAHgtgFglIAWAgQANAfAKAgQAJB2giBqIgDAEIABABIgNAhQgdgEgfgBIggAAQgZACgYAGQgSgegXgggAlNjFQD/i1DXCdQhDgThNAPQh+AXgtBpQhKhmhRACg");
	this.shape_196.setTransform(303.2,212.4);

	this.shape_197 = new cjs.Shape();
	this.shape_197.graphics.f("#B1D93D").s().p("ApRNCIgQgUIgiAXQjwCUjNiHQgsgdgqgqQg+AohGAfQhIAghSAVQh8AihZgrQgWgLgTgPQgtgkgig8IgDgFQgbgzgTgwQg3iLAQh1QAXicB2h9QApgsA2ggIASgKQBggyCEgRQCMgSBpAqQBAAbAzAwQAVioBIhIQBZhYBwgfQAmgKAngDQAXgCAXAAQAtAAAoAKQBXABBRgLQB3gSBDgjQBUgsABhHQAkAHAmAAQAii9CvgoQBLggBlAZIAgAJQAxicBshBQA8glBPgIQCzgFB9BvQEYkqFwC+QDJANAnCvQAZCRh5BLQAaCmhcBcQipCai3g+QgUBkhQBGQhcAOhNAkQg6AbgwAoIgVAEQhqANg+hDQg1BRh3AFQhqA5hbgcIgBgBIADgEQBAhkgnh7QgKgggMggIgXggQAFAmgHAtQgOBcgnAzQgUAbgcAPQg7AhgPgDQAYAgARAeQAkA9AMA2QAFAYABAWQAGCijqBUQAbEqkNBpQhAAZg/AAQiuAAicjCgAgxjHQAthpB9gXQBOgPBDATQjYidj+C2IAFAAQBOAABIBjg");
	this.shape_197.setTransform(290.3,222.6);

	this.shape_198 = new cjs.Shape();
	this.shape_198.graphics.f("#7AA234").s().p("AkUBRIANgiQBbAdBqg5QB2gGA1hPQA+BCBqgNIAEAOQi5ANicCnQhbhRh5gTgAjsi0QAnB7hABkQAjhpgKh2g");
	this.shape_198.setTransform(360.1,233.5);

	this.shape_199 = new cjs.Shape();
	this.shape_199.graphics.f("#B3BE35").s().p("AxQOQQhnADhighQjEBUith1QhbAehoAWQhrAWhXgLQgYAFgYACQhPAHg/geQgWgKgTgQQgwglgihAQhOiQgJh5QgEguAGgrQAXidB2h9QB2h9DfgcQBRgKBEAKIAogFQBngKBZAKQALgnAQgfQgqgIgngFQAhABAfAEIARACIAAAFQATgnAagaQBfheB6gcQDNCHDwiUIAygDQDUEHD1heQEPhpgckqQDphUgFiiQgBgWgFgYQgMg2gkg9QAXgGAagCIAgAAQAfABAdAFQB5ATBbBRQCdinC4gOQCRgLCiBUQBkAGA8AvIAbANQAgARAdAUIAfgZQAfgXAfgTQFJjQGiCnQEEANAyCvQAiCRieBLQAiCmh3BcQhjBFhnAaQh8AeiCghQgJAhgRAfQgjA7hEAvQhmC+jAhyQjcBAhYhJQhEBQibAGIgmAOQg1ASgyAEQg9AFg3gNQBDhNgNhaQhCAOg5AcQghAwg1AWQhMAggTgDQBbBhAYBQQAHAYABAXQABAggLAeQgpBsjUBCIghAJIABALQAHBEgOA6QgFAVgIAUQg5CQjKBGIgkAMQhcAbhZgDQiKgEiBhOQgwAlhCAaQhAAYg/AAQiIAAh9h2g");
	this.shape_199.setTransform(312.3,336);

	this.shape_200 = new cjs.Shape();
	this.shape_200.graphics.f("#C5D644").s().p("EgkBAKsQAZiTCNhwQAohaCShDQAagOAbgMQAegNAhgKQCkg1DVAcIAZAEQAAgEABgDQAKhLA8g0QBHgeA9gnQArApArAcQh6AchfBfQgaAagTAmIAAgEIgRgDQgfgEghgBQAnAFAqAIQgQAfgLAnQhZgKhnALIgoAEQhFgKhQALQjfAdh2B9Qh2B9gXCcQgGArAEAuQgThbAOhNgAqaAdIAPATIgyADIAjgWgAWDoXIgbgOQg8guhkgHQiihUiRALIgDgOIAUgDQAxgpA5gbQBZAZBJA+QEDjTFKAnQFPAUC6DaQmiimlJDPQgfAUgfAXIgfAYQgdgUgggQg");
	this.shape_200.setTransform(296,301.1);

	this.shape_201 = new cjs.Shape();
	this.shape_201.graphics.f("#A1BF37").s().p("ABfGhQgtARgrALQj7A+i4i4QjmCikEjYQDBkzFdB5QCLjbD0gOIAIAAQIIp7F6JXQAiEHiyDKQjEDHjfAAQh7AAiEg9g");
	this.shape_201.setTransform(325.7,391.1);

	this.shape_202 = new cjs.Shape();
	this.shape_202.graphics.f("#90A034").s().p("As+D6QAPADA7ghQBPgrAWiPQAKhBgPgxQAgA+AUBBQAnB+hDBmQBbAdBrg5QB3gFA1hRQBEBKB5gYQhWBHg5BvQgngLgnALQgVAEgSAGQhrAUhOgiQhlAOg5g8Qg8AUgBBAQgShQhHhhgAF9BXQhjgHhVANQBQhGAUhjQC3A+CpiaQBchcgaimQB6BigGCWQglCniNA8QhdAahVgaQADAcgSAUQgmgGgpgEg");
	this.shape_202.setTransform(323.7,320.1);

	this.shape_203 = new cjs.Shape();
	this.shape_203.graphics.f("#C5D644").s().p("A5jPnQg3g9g3iLQg0ioASiAQAYi6CoiCQDLjAEpBMQARkdENhSQDag/CUCfQBMiJBuAbQBbAPA1BdQATgsAhACQg8hkAUhqQAJjEDgg2IAcgGQBTgOBLAYQBajkDUgcQCxgkB7CGQCOiXCqgXQBFgKBJAMQEDATCPDbQkticjzCsQg1AmgzA2Qh9hvizAFQjbAWhND0Qh5gohXAmQiwAogiC+QCrggCbCGQA8AeAMA+QgOgPgSgLQhfg/h9AYQh9AYguBpQiSjOiyDaQhghviXAAQi+AAiGCFQhJBJgUCpQiJiCjfAdQjgAdh2B9Qh2B9gWCdQgXCcBrDGQAjBAAvAlIgIACQgXAAghgjg");
	this.shape_203.setTransform(202.4,315.5);

	this.shape_204 = new cjs.Shape();
	this.shape_204.graphics.f("#B6C461").s().p("AhiE2Qg9AOAAgkQhhALg6g3Qgigegag6QB3BUCjgtQB5gXAihwQAWg3gWg3QBEAUBIhCQAvgzgUgrQgEg3gSgRQgjgrgggFQAjgJAjAJQApAMAmATQAhATAbAzQATAkAAAsQANAvgTA2QjhA1gIDEQgbAbgqAPQgkAkgjgDQgfATgcAAQgPAAgOgFg");
	this.shape_204.setTransform(180,248.3);

	this.shape_205 = new cjs.Shape();
	this.shape_205.graphics.f("#D2E077").s().p("AjrFnQizg3gFjVQgEiTCMg0QAGg9A8glQBKgoA/ASQABhlCLghQBMgPBXAPQA3AIA0AzQAkAbAXAuQAbBHAFBHQglhZg4g5QhfhWhhArQibAtATB3Qg2gzhQA8QhDAmAmBJQimA8AWBsQAHBeBYARQAKBABjAVg");
	this.shape_205.setTransform(152,226.1);

	this.shape_206 = new cjs.Shape();
	this.shape_206.graphics.f("#CADC69").s().p("AjEE0IgKgHQhigVgLhAQhYgRgHheQgVhrClg8QgmhKBDgmQBRg8A2AzQgTh3CagtQBigrBeBWQA5A5AkBZQAgAEAjAsQASARAEA3QAUAqgvAzQhIBBhEgTQAXA3gXA4QgiBvh6AYQg5APgyAAQhgAAhNg2g");
	this.shape_206.setTransform(162.3,233.1);

	this.shape_207 = new cjs.Shape();
	this.shape_207.graphics.f("#B1D93D").s().p("AqiBZQBagYA+AYQAVisCUguQATgGAUgDQAngLAnALQA6hvBVhHQAwgoA4gcQBOglBdgNQBVgNBiAHQApADAmAGQEcAsBlClQAuBEAYBLQAMAlAGAmQl6pXoIJ6IgIAAQj0AOiLDcQldh6jBE0QgdkwENg2g");
	this.shape_207.setTransform(325.3,373.3);

	this.shape_208 = new cjs.Shape();
	this.shape_208.graphics.f("#7AA234").s().p("AgcIJQh2ABhpgoQhFgag/gsQgiAggxAJQhoAhgxhCQgggUgSgcQkMA+iojTQgogpgThGQgJgrgEgnQEEDYDmiiQC4C4D8g+QArgLAtgRQFwCsExk2QCyjJgikIQgGgmgMglQEIhFCeCmQC0CohaEHQiPEuldhQQhcDZj8g0QilBqiXAAIgYAAg");
	this.shape_208.setTransform(351.6,415);

	this.shape_209 = new cjs.Shape();
	this.shape_209.graphics.f("#939E36").s().p("AFYGbIg8gQQhgg1hCh6Qg7A3hCAQQg7AXh4AEQi9gjh6h9QihBgjJguQiHgdgzhEQBYArB9ghQChgrB8hQQD+D6E3jYQDaEeD+hhQEPhpgckqQDqhUgFihQBFBCAHBSQkNA2AdEvQAEAnAJArQhpEMjsAAQg8AAhGgRg");
	this.shape_209.setTransform(153.6,410.2);

	this.shape_210 = new cjs.Shape();
	this.shape_210.graphics.f("#B3BE35").s().p("AphMuQk3DZj+j8Qh9BRihArQh8AihZgrQgWgLgTgPQgwglgihAQhrjGAWidQAXicB2h9QB2h9DfgcQDggdCICAQAVioBIhIQCHiGC9AAQCXAABgBuQCyjZCUDNQAthpB9gXQB9gYBfA+QARAMAOAPQgMg/g7geQiciFipAfQAhi+CwgoQBWglB6AnQBNjzDbgXQCzgFB9BvQAzg2A1glQDyitEuCcQDJANAnCvQAZCRh5BLQAaCmhcBcQipCai3g+QgUBkhQBGQhdAOhNAkQg5AbgwAoQh5AYhEhKQg1BRh3AFQhrA5hbgdQBDhmgnh9QgUhCggg+QAPAxgKBCQgWCOhPArQg7AhgPgDQBHBhASBQQAFAYABAWQAGCijqBUQAbEqkNBpQhAAZg/AAQi3AAijjWg");
	this.shape_210.setTransform(216.7,332);

	this.shape_211 = new cjs.Shape();
	this.shape_211.graphics.f("#492513").s().p("AgJSyQiEhIh+hTQg5g2hzAaQhEhggViaIgZuHQAOk4BKkUQBhjWBgh1QBmAzChgrQBjgbB7g/QCiAICyhyQgoBHiyBcQixBAinCJIgPAMQhbAeinDcQhGB4gUD4QgUGqBLEeQBQE7CDC1QAtBQA0BDQAjAuAnApQASAcgSATIhKgog");
	this.shape_211.setTransform(327.5,580.8);

	this.shape_212 = new cjs.Shape();
	this.shape_212.graphics.f("#663300").s().p("AI/VgIjwh2QjJhIkqAHQjMAJi7BKQA0hJBRg/QBuhvBLiJQB9iPAKmVQAJlPgtlgQghjBg/iuQgviWhmhYQg4gvhfgvQiZhiighVQB4gEA7gXQCJA+CXAqIA8AQQFSBXCElSQATBGAoApQB5HWFtkRQAxBCBoghQhFBYAVA+QhgB2hgDVQhLEUgNE3IAZOIQAUCaBEBgQhsgFgEA8QAJBYB4A1QgIAIgTAAQgTAAgdgIg");
	this.shape_212.setTransform(220.1,564.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).to({state:[{t:this.shape_13},{t:this.shape_12,p:{x:259.6,y:538.8}}]},1).to({state:[{t:this.shape_15},{t:this.shape_14,p:{x:241.2,y:513.2}}]},2).to({state:[{t:this.shape_17},{t:this.shape_12,p:{x:231.6,y:495.6}},{t:this.shape_16}]},2).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18}]},2).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21}]},1).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24}]},1).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_27,p:{y:450.3}}]},1).to({state:[{t:this.shape_26},{t:this.shape_28},{t:this.shape_14,p:{x:218,y:448.4}}]},1).to({state:[{t:this.shape_26},{t:this.shape_29},{t:this.shape_14,p:{x:218.4,y:451.1}}]},1).to({state:[{t:this.shape_26},{t:this.shape_30},{t:this.shape_27,p:{y:451.3}}]},1).to({state:[{t:this.shape_30},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31}]},1).to({state:[{t:this.shape_30},{t:this.shape_35},{t:this.shape_34},{t:this.shape_31}]},1).to({state:[{t:this.shape_30},{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_30},{t:this.shape_39},{t:this.shape_37},{t:this.shape_38}]},1).to({state:[{t:this.shape_30},{t:this.shape_41},{t:this.shape_37},{t:this.shape_40}]},1).to({state:[{t:this.shape_43},{t:this.shape_30},{t:this.shape_37},{t:this.shape_42}]},1).to({state:[{t:this.shape_48},{t:this.shape_30},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44}]},1).to({state:[{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_47}]},2).to({state:[{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_51},{t:this.shape_54}]},2).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58}]},1).to({state:[{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63}]},1).to({state:[{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68}]},1).to({state:[{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73}]},1).to({state:[{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78}]},2).to({state:[{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89}]},1).to({state:[{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100}]},1).to({state:[{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111}]},1).to({state:[{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122}]},3).to({state:[{t:this.shape_125},{t:this.shape_124},{t:this.shape_122},{t:this.shape_133},{t:this.shape_132},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_131}]},1).to({state:[{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134}]},1).to({state:[{t:this.shape_151},{t:this.shape_150},{t:this.shape_149},{t:this.shape_148},{t:this.shape_147},{t:this.shape_146},{t:this.shape_145},{t:this.shape_144},{t:this.shape_143}]},1).to({state:[{t:this.shape_160},{t:this.shape_159},{t:this.shape_158},{t:this.shape_157},{t:this.shape_156},{t:this.shape_155},{t:this.shape_154},{t:this.shape_153},{t:this.shape_152}]},1).to({state:[{t:this.shape_169},{t:this.shape_168},{t:this.shape_167},{t:this.shape_166},{t:this.shape_165},{t:this.shape_164},{t:this.shape_163},{t:this.shape_162},{t:this.shape_161}]},1).to({state:[{t:this.shape_177},{t:this.shape_176},{t:this.shape_167},{t:this.shape_165},{t:this.shape_166},{t:this.shape_175},{t:this.shape_174},{t:this.shape_173},{t:this.shape_161},{t:this.shape_172},{t:this.shape_171},{t:this.shape_170}]},2).to({state:[{t:this.shape_177},{t:this.shape_176},{t:this.shape_171},{t:this.shape_182},{t:this.shape_181},{t:this.shape_167},{t:this.shape_165},{t:this.shape_166},{t:this.shape_180},{t:this.shape_179},{t:this.shape_178},{t:this.shape_161}]},2).to({state:[{t:this.shape_192},{t:this.shape_191},{t:this.shape_190},{t:this.shape_189},{t:this.shape_188},{t:this.shape_187},{t:this.shape_186},{t:this.shape_166},{t:this.shape_185},{t:this.shape_184},{t:this.shape_183},{t:this.shape_161}]},2).to({state:[{t:this.shape_200},{t:this.shape_199},{t:this.shape_198},{t:this.shape_197},{t:this.shape_196},{t:this.shape_187},{t:this.shape_186},{t:this.shape_166},{t:this.shape_195},{t:this.shape_194},{t:this.shape_193},{t:this.shape_161}]},1).to({state:[{t:this.shape_212},{t:this.shape_211},{t:this.shape_210},{t:this.shape_209},{t:this.shape_208},{t:this.shape_207},{t:this.shape_206},{t:this.shape_205},{t:this.shape_204},{t:this.shape_203},{t:this.shape_202},{t:this.shape_201}]},1).to({state:[]},8).wait(6));

	// Layer 4
	this.play_btn = new lib.play_btn();
	this.play_btn.parent = this;
	this.play_btn.setTransform(476,952.7,1,1,0,0,0,84,35.8);
	new cjs.ButtonHelper(this.play_btn, 0, 1, 2, false, new lib.play_btn(), 3);

	this.shape_213 = new cjs.Shape();
	this.shape_213.graphics.lf(["#6BFFFF","#0087F0"],[0,1],0,301.9,0,-301.8).s().p("Egy3AxoMAAAhjPMBlvAAAMAAABjPg");
	this.shape_213.setTransform(320.4,312.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_213},{t:this.play_btn}]}).wait(72));

	// Layer 5
	this.shape_214 = new cjs.Shape();
	this.shape_214.graphics.lf(["#6B6110","#00CA1F"],[0,1],0,323,0,-323).s().p("EgydAsXMAAAhYtMBk7AAAMAAABYtg");
	this.shape_214.setTransform(317.8,851.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_214).wait(72));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(314.8,562.9,651.2,1140.9);
// library properties:
lib.properties = {
	width: 640,
	height: 1136,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;